export const INDUSTRIES_CATALOG = [
  "Fintech",
  "Healthtech",
  "Edtech",
  "Logística",
  "Consumer",
  "B2B",
  "B2B SaaS",
  "SaaS",
  "DevTools",
  "AI",
  "Climate",
  "DeepTech",
  "Crypto",
  "Marketplace",
  "Infra",
  "Gaming",
  "Hardware",
  "E-commerce",
  "Retail",
  "Real Estate",
  "Proptech",
  "Legaltech",
  "Insurtech",
  "Agtech",
  "Foodtech",
  "Traveltech",
  "Cybersecurity",
  "Data",
  "Analytics",
  "HRTech",
  "Creator Economy",
  "Media",
  "Entertainment",
  "Biotech",
  "Robotics",
  "Energía",
  "Movilidad",
  "Transporte",
  "Supply Chain",
  "Manufactura",
  "Construcción",
  "Educación",
  "Salud",
  "Wellness",
  "Sports",
  "Comunidad",
  "Productividad",
  "Finanzas personales",
  "Pagos",
  "Lending",
  "Open Finance",
  "GovTech",
  "Impacto social",
  "Sostenibilidad",
  "Aeroespacial",
  "Telecom",
  "Seguros",
  "Recruiting",
  "Ventas",
  "Marketing",
  "No-code",
  "Web3",
  "IoT",
  "AR/VR",
] as const

export const WORLDWIDE_CITY_LABEL = "Todo el mundo" as const

export const CITIES_CATALOG = [
  WORLDWIDE_CITY_LABEL,
  "Ciudad de México",
  "Guadalajara",
  "Monterrey",
  "Querétaro",
  "Puebla",
  "Tijuana",
  "Mérida",
  "León",
  "Toluca",
  "Cancún",
  "Aguascalientes",
  "San Luis Potosí",
  "Chihuahua",
  "Hermosillo",
  "Saltillo",
  "Culiacán",
  "Morelia",
  "Oaxaca",
  "Veracruz",
  "Torreón",
  "Mexicali",
  "Ciudad Juárez",
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Bucaramanga",
  "Pereira",
  "Manizales",
  "Santa Marta",
  "Cúcuta",
  "Miami",
  "San Francisco",
  "New York",
  "Los Angeles",
  "Austin",
  "Seattle",
  "Boston",
  "Chicago",
  "Houston",
  "Dallas",
  "Denver",
  "Atlanta",
  "Washington DC",
  "San Diego",
  "Phoenix",
  "Lima",
  "Buenos Aires",
  "Santiago",
  "São Paulo",
  "Rio de Janeiro",
  "Montevideo",
  "Asunción",
  "Quito",
  "Guayaquil",
  "La Paz",
  "Santa Cruz",
  "San José",
  "Panamá",
  "Santo Domingo",
  "San Juan",
  "San Salvador",
  "Guatemala",
  "Tegucigalpa",
  "Managua",
  "Caracas",
  "Maracaibo",
  "La Habana",
  "Brasília",
  "Curitiba",
  "Florianópolis",
  "Porto Alegre",
  "Recife",
] as const

/** Stable slug for `industries_catalog.slug` / `search_industries.industry_slug`. */
export function industryLabelToSlug(label: string): string {
  return label
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

export function industrySlugToLabel(
  slug: string,
  catalog: readonly string[] = INDUSTRIES_CATALOG
): string {
  const found = catalog.find((label) => industryLabelToSlug(label) === slug)
  return (
    found ??
    slug
      .split("-")
      .filter(Boolean)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ")
  )
}
