import type {
  Chat,
  CurrentUser,
  EventEntry,
  IgnoredConnection,
  Profile,
  ReceivedConnection,
  Search,
  SentConnection,
} from "./types"

export const mockProfiles: Profile[] = [
  {
    id: "p1",
    name: "Lucía Hernández",
    initials: "LH",
    role: "Senior Product Engineer",
    bio: "Construyendo herramientas para equipos pequeños. Antes en Stripe y Cabify. Buscando un proyecto técnico con tracción real para sumarme como co-founder.",
    area: "tecnico",
    experience: "6-10",
    achievement: "Rediseñé un checkout y subí la conversión 22%",
    availability: "full-time",
    industries: ["Fintech", "DevTools"],
    workStyle: ["remoto", "rapido", "async"],
    city: "Ciudad de México",
    relationsLooking: ["co-founder"],
    compatibility: "alta",
    online: true,
    eventCodes: ["BLDR26", "MTYDEV"],
  },
  {
    id: "p2",
    name: "Diego Romero",
    initials: "DR",
    role: "Founder en stealth · Healthtech",
    bio: "Construyendo una plataforma de salud preventiva en LatAm. Médico cirujano + MBA. Busco CTO técnico que ya haya enviado producto a producción.",
    area: "negocio",
    experience: "10+",
    achievement: "Levanté $1.2M pre-seed con 3 hospitales firmados",
    availability: "full-time",
    industries: ["Healthtech", "B2B"],
    workStyle: ["hibrido", "estructurado"],
    city: "Monterrey",
    relationsLooking: ["co-founder", "empleo"],
    compatibility: "alta",
    online: false,
    eventCodes: ["BLDR26"],
  },
  {
    id: "p3",
    name: "Mariana López",
    initials: "ML",
    role: "Senior Product Designer",
    bio: "Diseño producto end-to-end. 8 años en startups de consumo. Buscando equipo con cultura de research y experimentación.",
    area: "producto",
    experience: "6-10",
    achievement: "Lancé una app que llegó a 500k descargas en 4 meses",
    availability: "part-time",
    industries: ["Consumer", "Fintech"],
    workStyle: ["remoto", "estructurado"],
    city: "Guadalajara",
    relationsLooking: ["co-founder", "empleo", "colaboracion"],
    compatibility: "media",
    online: true,
    eventCodes: ["BLDR26", "LATAM7"],
  },
  {
    id: "p4",
    name: "Andrés Velázquez",
    initials: "AV",
    role: "Mentor · Ex-VP Eng",
    bio: "Construí equipos de ingeniería de 0 a 50+ en 3 startups. Hoy advisor y angel. Me encanta acompañar founders técnicos en sus primeros 18 meses.",
    area: "tecnico",
    experience: "10+",
    achievement: "Construí equipos de ingeniería en dos exits, uno por $80M",
    availability: "3-6m",
    industries: ["DevTools", "B2B", "Infra"],
    workStyle: ["async", "rapido"],
    city: "Ciudad de México",
    relationsLooking: ["mentoria", "inversion"],
    compatibility: "alta",
  },
  {
    id: "p5",
    name: "Sofía Cárdenas",
    initials: "SC",
    role: "Growth Lead",
    bio: "Especialista en growth para startups B2C en LatAm. Buscando primer equipo fundador para sumarme en stage muy temprano.",
    area: "negocio",
    experience: "3-5",
    achievement: "Llevé una app de 1k a 100k DAUs en 9 meses",
    availability: "full-time",
    industries: ["Consumer", "Edtech"],
    workStyle: ["remoto", "rapido"],
    city: "Bogotá",
    relationsLooking: ["co-founder", "empleo"],
    compatibility: "media",
    online: true,
    eventCodes: ["LATAM7"],
  },
  {
    id: "p6",
    name: "Tomás Ríos",
    initials: "TR",
    role: "Full-stack Engineer",
    bio: "Builder, prefiero shippear que reunir. TypeScript, Postgres, Rust. Vengo de fintech, quiero construir algo en climate o DeepTech.",
    area: "tecnico",
    experience: "3-5",
    achievement: "Crecí un side project a 12k usuarios sin marketing",
    availability: "full-time",
    industries: ["Climate", "DeepTech"],
    workStyle: ["async", "remoto"],
    city: "Buenos Aires",
    relationsLooking: ["co-founder", "empleo", "colaboracion"],
    compatibility: "alta",
    online: false,
    eventCodes: ["BLDR26", "LATAM7"],
  },
  {
    id: "p7",
    name: "Valentina Mejía",
    initials: "VM",
    role: "Médica · Especialista en oncología",
    bio: "10 años en práctica clínica. Busco aplicar mi expertise a una startup que esté resolviendo de verdad el acceso a tratamientos.",
    area: "ciencia",
    experience: "10+",
    achievement: "Soy co-autora de 14 papers indexados",
    availability: "part-time",
    industries: ["Healthtech"],
    workStyle: ["estructurado", "presencial"],
    city: "Medellín",
    relationsLooking: ["mentoria", "colaboracion", "abierto"],
    compatibility: "media",
  },
  {
    id: "p8",
    name: "Rodrigo Aguirre",
    initials: "RA",
    role: "Angel investor",
    bio: "Ex-founder, ahora invierto cheques de $25k–$100k en pre-seed LatAm. Foco en B2B SaaS y fintech.",
    area: "negocio",
    experience: "10+",
    achievement: "He invertido en 12 startups, con 3 unicornios en portfolio",
    availability: "3-6m",
    industries: ["Fintech", "B2B", "DevTools"],
    workStyle: ["async"],
    city: "Ciudad de México",
    relationsLooking: ["inversion", "mentoria"],
    compatibility: "alta",
    online: true,
    eventCodes: ["LATAM7", "MTYDEV"],
  },
  {
    id: "p9",
    name: "Camila Soto",
    initials: "CS",
    role: "Operations · Logística",
    bio: "Construí operaciones desde cero en startup de last-mile. Lista para un siguiente reto fundacional.",
    area: "operaciones",
    experience: "3-5",
    achievement: "Escalé una operación de 3 a 18 ciudades en 14 meses",
    availability: "full-time",
    industries: ["Logística", "Consumer"],
    workStyle: ["hibrido", "rapido"],
    city: "Lima",
    relationsLooking: ["co-founder", "empleo"],
    compatibility: "baja",
  },
  {
    id: "p10",
    name: "Juan Pablo Serra",
    initials: "JP",
    role: "Data Scientist",
    bio: "ML aplicado a producto. ICML 2024. Busco proyectos donde el modelo sea producto, no commodity.",
    area: "tecnico",
    experience: "3-5",
    achievement: "Puse en producción un modelo con 2.4M inferencias al día",
    availability: "part-time",
    industries: ["AI", "DeepTech"],
    workStyle: ["remoto", "estructurado"],
    city: "Santiago",
    relationsLooking: ["co-founder", "colaboracion"],
    compatibility: "media",
    online: false,
  },
]

export const mockSearches: Search[] = [
  {
    id: "s1",
    title: "Co-founder técnico (CTO)",
    description:
      "Busco co-founder técnico para una plataforma de salud preventiva. Idealmente alguien que haya enviado producto a producción y quiera tomar 50% de equity.",
    relations: ["co-founder"],
    area: "tecnico",
    industries: ["Healthtech", "B2B"],
    status: "active",
    matchesCount: 4,
    createdAt: "2026-04-10",
  },
  {
    id: "s2",
    title: "Primer diseñador de producto",
    description:
      "Diseñador full-time para sumarse al equipo fundador. Trabajo end-to-end, decisiones rápidas, ownership total del producto.",
    relations: ["empleo"],
    area: "producto",
    industries: ["Healthtech"],
    status: "active",
    matchesCount: 2,
    createdAt: "2026-04-15",
  },
  {
    id: "s3",
    title: "Advisor en regulación de salud",
    description:
      "Mentor con experiencia en regulación COFEPRIS / FDA para acompañarnos en compliance.",
    relations: ["mentoria"],
    area: "ciencia",
    industries: ["Healthtech"],
    status: "paused",
    matchesCount: 1,
    createdAt: "2026-03-22",
  },
]

export const mockReceivedConnections: ReceivedConnection[] = [
  {
    id: "rc1",
    profile: mockProfiles[0],
    relation: "co-founder",
    searchTitle: "Co-founder técnico (CTO)",
    message:
      "Hola! Vi tu búsqueda de CTO y resuena mucho con lo que busco. Vengo de Stripe construyendo infra de pagos. Me encantaría platicar 30 min sobre tu visión y ver si hay match. Disponible esta semana.",
    receivedAt: "2026-04-26",
  },
  {
    id: "rc2",
    profile: mockProfiles[3],
    relation: "mentoria",
    searchTitle: "Advisor en regulación de salud",
    message:
      "Pude acompañar a 3 founders de healthtech con regulación. Si te sirve, podemos agendar una sesión inicial sin costo para ver si tiene sentido seguir trabajando juntos.",
    receivedAt: "2026-04-25",
  },
  {
    id: "rc3",
    profile: mockProfiles[5],
    relation: "empleo",
    searchTitle: "Primer diseñador de producto",
    message:
      "Aunque mi rol es ingeniería, también he hecho diseño en startups tempranas y conozco a 2-3 diseñadores que están buscando. Me gustaría conectar.",
    receivedAt: "2026-04-23",
  },
]

export const mockSentConnections: SentConnection[] = [
  {
    id: "sc1",
    profile: mockProfiles[2],
    relation: "empleo",
    message:
      "Hola Mariana, vi que buscas equipo con research. Estamos construyendo Murmur y necesitamos un líder de diseño. ¿Podemos platicar?",
    status: "pending",
    sentAt: "2026-04-26",
  },
  {
    id: "sc2",
    profile: mockProfiles[4],
    relation: "co-founder",
    message:
      "Hola Sofía, tu trayectoria de growth me parece increíble. Quiero co-construir algo en consumer LatAm. Te invito a que conversemos.",
    status: "accepted",
    sentAt: "2026-04-22",
  },
  {
    id: "sc3",
    profile: mockProfiles[8],
    relation: "empleo",
    message:
      "Camila, necesitamos a alguien que pueda construir operaciones desde cero. Tu experiencia con last-mile encaja perfecto.",
    status: "rejected",
    sentAt: "2026-04-18",
  },
]

export const mockIgnoredConnections: IgnoredConnection[] = [
  {
    id: "ic1",
    profile: mockProfiles[9],
    relation: "colaboracion",
    ignoredAt: "2026-04-20",
  },
]

export const mockChats: Chat[] = [
  {
    id: "c1",
    profile: mockProfiles[4],
    unread: 2,
    lastSeen: "Ahora",
    messages: [
      {
        id: "m1",
        fromMe: true,
        text: "Hola Sofía, gracias por aceptar la conexión.",
        sentAt: "2026-04-26T10:01:00",
      },
      {
        id: "m2",
        fromMe: false,
        text: "¡Hola! Claro, me intriga mucho lo que están construyendo en Murmur.",
        sentAt: "2026-04-26T10:04:00",
      },
      {
        id: "m3",
        fromMe: true,
        text: "Te puedo mandar el deck para que lo veas antes de la llamada?",
        sentAt: "2026-04-26T10:05:00",
      },
      {
        id: "m4",
        fromMe: false,
        text: "Sí, va.",
        sentAt: "2026-04-26T10:05:00",
      },
      {
        id: "m5",
        fromMe: false,
        text: "¿Y tienen métricas de activación de los primeros usuarios?",
        sentAt: "2026-04-27T18:50:00",
      },
    ],
  },
  {
    id: "c2",
    profile: mockProfiles[0],
    unread: 0,
    lastSeen: "Hace 2h",
    messages: [
      {
        id: "m6",
        fromMe: false,
        text: "Listo, agendado para el martes 4pm.",
        sentAt: "2026-04-26T15:22:00",
      },
      {
        id: "m7",
        fromMe: true,
        text: "Perfecto, te paso el link.",
        sentAt: "2026-04-26T15:30:00",
      },
    ],
  },
  {
    id: "c3",
    profile: mockProfiles[7],
    unread: 0,
    lastSeen: "Hace 1 día",
    messages: [
      {
        id: "m8",
        fromMe: false,
        text: "Veo potencial. Mándame el memo y lo reviso esta semana.",
        sentAt: "2026-04-25T09:00:00",
      },
    ],
  },
  {
    id: "c4",
    profile: mockProfiles[3],
    unread: 1,
    lastSeen: "Hace 30 min",
    messages: [
      {
        id: "m9",
        fromMe: false,
        text: "Gracias por aceptar. Te puedo compartir aprendizajes de regulación y primeras ventas en healthtech.",
        sentAt: "2026-04-27T18:18:00",
      },
    ],
  },
  {
    id: "c5",
    profile: mockProfiles[5],
    unread: 1,
    lastSeen: "Ahora",
    messages: [
      {
        id: "m10",
        fromMe: false,
        text: "¡Gracias por conectar! Vi tu búsqueda y creo que puedo aportar desde producto e ingeniería.",
        sentAt: "2026-04-27T19:05:00",
      },
    ],
  },
]

export function chatIdForProfile(profileId: string): string | undefined {
  return mockChats.find((c) => c.profile.id === profileId)?.id
}

export const mockCurrentUser: CurrentUser = {
  id: "me",
  name: "Carlos Salinas",
  initials: "CS",
  email: "carlos@murmur.app",
  role: "Founder en Murmur",
  bio: "Construyendo Murmur. Antes founder de 2 startups consumer. Curioso, async, rápido.",
  area: "negocio",
  experience: "6-10",
  achievement: "Levantó pre-seed sin pitch deck en 3 semanas",
  availability: "full-time",
  industries: ["B2B", "Consumer", "AI"],
  workStyle: ["remoto", "rapido", "async"],
  city: "Ciudad de México",
  cities: ["Ciudad de México", "Guadalajara", "Monterrey"],
  searchRadiusKm: 50,
  relationsLooking: ["co-founder", "empleo", "mentoria"],
  plan: "free",
  stats: {
    matches: 24,
    connections: 7,
    messages: 12,
  },
}

export const INDUSTRIES_CATALOG = [
  "Fintech",
  "Healthtech",
  "Edtech",
  "Logística",
  "Consumer",
  "B2B",
  "B2B SaaS",
  "SaaS",
  "DevTools",
  "AI",
  "Climate",
  "DeepTech",
  "Crypto",
  "Marketplace",
  "Infra",
  "Gaming",
  "Hardware",
  "E-commerce",
  "Retail",
  "Real Estate",
  "Proptech",
  "Legaltech",
  "Insurtech",
  "Agtech",
  "Foodtech",
  "Traveltech",
  "Cybersecurity",
  "Data",
  "Analytics",
  "HRTech",
  "Creator Economy",
  "Media",
  "Entertainment",
  "Biotech",
  "Robotics",
  "Energía",
  "Movilidad",
  "Transporte",
  "Supply Chain",
  "Manufactura",
  "Construcción",
  "Educación",
  "Salud",
  "Wellness",
  "Sports",
  "Comunidad",
  "Productividad",
  "Finanzas personales",
  "Pagos",
  "Lending",
  "Open Finance",
  "GovTech",
  "Impacto social",
  "Sostenibilidad",
  "Aeroespacial",
  "Telecom",
  "Seguros",
  "Recruiting",
  "Ventas",
  "Marketing",
  "No-code",
  "Web3",
  "IoT",
  "AR/VR",
] as const

export const CITIES_CATALOG = [
  "Ciudad de México",
  "Guadalajara",
  "Monterrey",
  "Querétaro",
  "Puebla",
  "Tijuana",
  "Mérida",
  "León",
  "Toluca",
  "Cancún",
  "Aguascalientes",
  "San Luis Potosí",
  "Chihuahua",
  "Hermosillo",
  "Saltillo",
  "Culiacán",
  "Morelia",
  "Oaxaca",
  "Veracruz",
  "Torreón",
  "Mexicali",
  "Ciudad Juárez",
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Bucaramanga",
  "Pereira",
  "Manizales",
  "Santa Marta",
  "Cúcuta",
  "Miami",
  "San Francisco",
  "New York",
  "Los Angeles",
  "Austin",
  "Seattle",
  "Boston",
  "Chicago",
  "Houston",
  "Dallas",
  "Denver",
  "Atlanta",
  "Washington DC",
  "San Diego",
  "Phoenix",
  "Lima",
  "Buenos Aires",
  "Santiago",
  "São Paulo",
  "Rio de Janeiro",
  "Montevideo",
  "Asunción",
  "Quito",
  "Guayaquil",
  "La Paz",
  "Santa Cruz",
  "San José",
  "Panamá",
  "Santo Domingo",
  "San Juan",
  "San Salvador",
  "Guatemala",
  "Tegucigalpa",
  "Managua",
  "Caracas",
  "Maracaibo",
  "La Habana",
  "Brasília",
  "Curitiba",
  "Florianópolis",
  "Porto Alegre",
  "Recife",
] as const

export const mockEvents: EventEntry[] = [
  {
    code: "BLDR26",
    name: "BuilderConf 2026",
    description: "Conferencia anual de builders en LatAm.",
  },
  {
    code: "LATAM7",
    name: "LatAm Founders Mixer",
    description: "Mixer de founders LatAm conectando 7 ciudades.",
  },
  {
    code: "MTYDEV",
    name: "MTY Dev Night",
    description: "Encuentro de ingeniería en Monterrey.",
  },
]

export function findEventByCode(code: string): EventEntry | undefined {
  const normalized = code.trim().toUpperCase()
  return mockEvents.find((event) => event.code === normalized)
}

export function profilesByEventCode(code: string): Profile[] {
  const normalized = code.trim().toUpperCase()
  return mockProfiles.filter((profile) =>
    profile.eventCodes?.includes(normalized)
  )
}
