-- Ampliar catálogo de ciudades (FK profile_cities). «Todo el mundo» no es ciudad principal.

INSERT INTO public.cities_catalog (slug, name, sort_order, country) VALUES
  ('zapopan', 'Zapopan', 10, 'MX'),
  ('tepic', 'Tepic', 11, 'MX'),
  ('pachuca', 'Pachuca', 12, 'MX'),
  ('cuernavaca', 'Cuernavaca', 13, 'MX'),
  ('villahermosa', 'Villahermosa', 14, 'MX'),
  ('xalapa', 'Xalapa', 15, 'MX'),
  ('durango', 'Durango', 16, 'MX'),
  ('colima', 'Colima', 17, 'MX'),
  ('ensenada', 'Ensenada', 18, 'MX'),
  ('puerto-vallarta', 'Puerto Vallarta', 19, 'MX'),
  ('nuevo-laredo', 'Nuevo Laredo', 20, 'MX'),
  ('reynosa', 'Reynosa', 21, 'MX'),
  ('matamoros', 'Matamoros', 22, 'MX'),
  ('la-paz', 'La Paz', 23, 'MX'),
  ('campeche', 'Campeche', 24, 'MX'),
  ('chetumal', 'Chetumal', 25, 'MX'),
  ('tuxtla-gutierrez', 'Tuxtla Gutiérrez', 26, 'MX'),
  ('irapuato', 'Irapuato', 27, 'MX'),
  ('merida', 'Mérida', 28, 'MX'),
  ('queretaro', 'Querétaro', 29, 'MX'),
  ('puebla', 'Puebla', 30, 'MX'),
  ('tijuana', 'Tijuana', 31, 'MX'),
  ('leon', 'León', 32, 'MX'),
  ('toluca', 'Toluca', 33, 'MX'),
  ('cancun', 'Cancún', 34, 'MX'),
  ('aguascalientes', 'Aguascalientes', 35, 'MX'),
  ('san-luis-potosi', 'San Luis Potosí', 36, 'MX'),
  ('chihuahua', 'Chihuahua', 37, 'MX'),
  ('hermosillo', 'Hermosillo', 38, 'MX'),
  ('saltillo', 'Saltillo', 39, 'MX'),
  ('culiacan', 'Culiacán', 40, 'MX'),
  ('morelia', 'Morelia', 41, 'MX'),
  ('oaxaca', 'Oaxaca', 42, 'MX'),
  ('veracruz', 'Veracruz', 43, 'MX'),
  ('torreon', 'Torreón', 44, 'MX'),
  ('mexicali', 'Mexicali', 45, 'MX'),
  ('ciudad-juarez', 'Ciudad Juárez', 46, 'MX')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order,
  country = EXCLUDED.country;
