-- Expertise = roles por industria; max 3 en perfil/búsqueda. Generado desde lib/industry-expertise-role-seeds.ts
BEGIN;

DELETE FROM public.expertise_catalog;

INSERT INTO public.expertise_catalog (slug, industry_slug, label, sort_order, maps_to, vertical_slug) VALUES

  ('tecnologia-ia-product-manager', 'tecnologia-ia', 'Product manager', 10, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-product-owner', 'tecnologia-ia', 'Product owner', 20, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-project-manager', 'tecnologia-ia', 'Project manager / entrega', 30, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-engineering-manager', 'tecnologia-ia', 'Engineering manager', 40, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-tech-lead', 'tecnologia-ia', 'Tech lead', 50, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-staff-principal-engineer', 'tecnologia-ia', 'Staff / principal engineer', 60, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-cto-vp-engineering', 'tecnologia-ia', 'CTO / VP Engineering', 70, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-backend-developer', 'tecnologia-ia', 'Backend developer', 80, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-frontend-developer', 'tecnologia-ia', 'Frontend developer', 90, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-fullstack-developer', 'tecnologia-ia', 'Full‑stack developer', 100, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-mobile-developer', 'tecnologia-ia', 'Mobile developer', 110, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-devops-sre', 'tecnologia-ia', 'DevOps / SRE', 120, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-data-engineer', 'tecnologia-ia', 'Data engineer', 130, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-ml-engineer', 'tecnologia-ia', 'Machine learning engineer', 140, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-qa-engineer', 'tecnologia-ia', 'QA / tester', 150, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-security-engineer', 'tecnologia-ia', 'Security engineer', 160, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-ux-designer', 'tecnologia-ia', 'UX designer', 170, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-ui-designer', 'tecnologia-ia', 'UI designer', 180, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-ux-researcher', 'tecnologia-ia', 'UX researcher', 190, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-solution-architect', 'tecnologia-ia', 'Solution architect', 200, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-technical-writer', 'tecnologia-ia', 'Technical writer', 210, 'tecnico', 'tecnologia-ia-general'),
  ('tecnologia-ia-solutions-sales-engineer', 'tecnologia-ia', 'Solutions / sales engineer', 220, 'tecnico', 'tecnologia-ia-general'),
  ('salud-biotech-medico-clinico', 'salud-biotech', 'Médico(a) clínico(a)', 10, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-enfermeria-practica', 'salud-biotech', 'Enfermería (práctica)', 20, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-cirujano', 'salud-biotech', 'Cirujano(a)', 30, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-investigador-clinico', 'salud-biotech', 'Investigador(a) clínico(a) / CRO', 40, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-farmaceutico', 'salud-biotech', 'Farmacéutico(a)', 50, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-tecnico-laboratorio-biomedico', 'salud-biotech', 'Técnico(a) / biólogo(a) de laboratorio', 60, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-fisioterapeuta', 'salud-biotech', 'Fisioterapeuta', 70, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-psicologo-clinico', 'salud-biotech', 'Psicólogo(a) clínico(a)', 80, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-director-medico', 'salud-biotech', 'Director(a) médico(a)', 90, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-gestor-sanitario', 'salud-biotech', 'Gestor(a) sanitario(a)', 100, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-regulatory-affairs', 'salud-biotech', 'Regulatory affairs / calidad clínica', 110, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-msl-medical-science', 'salud-biotech', 'MSL / medical affairs', 120, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-epidemiologo', 'salud-biotech', 'Epidemiología / salud pública', 130, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-veterinario', 'salud-biotech', 'Veterinario(a)', 140, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-odontologo', 'salud-biotech', 'Odontólogo(a)', 150, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-jefe-enfermeria', 'salud-biotech', 'Jefe(a) / coordinación de enfermería', 160, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-tecnico-imagen-radiologia', 'salud-biotech', 'Técnico(a) de imagen / radiología', 170, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-nutricionista-clinico', 'salud-biotech', 'Nutrición clínica', 180, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-gerente-operaciones-clinica', 'salud-biotech', 'Gerente operaciones clínica / hospital', 190, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-product-manager-salud-digital', 'salud-biotech', 'Product manager salud digital', 200, 'ciencia', 'salud-biotech-general'),
  ('salud-biotech-data-analyst-salud', 'salud-biotech', 'Data analyst en salud', 210, 'ciencia', 'salud-biotech-general'),
  ('educacion-docente-aula', 'educacion', 'Docente frente a grupo', 10, 'producto', 'educacion-general'),
  ('educacion-coordinador-academico', 'educacion', 'Coordinador(a) académico(a)', 20, 'producto', 'educacion-general'),
  ('educacion-director-escuela', 'educacion', 'Director(a) de escuela / centro', 30, 'producto', 'educacion-general'),
  ('educacion-gestion-universitaria', 'educacion', 'Gestión universitaria / rectoría', 40, 'producto', 'educacion-general'),
  ('educacion-disenador-instruccional', 'educacion', 'Diseñador(a) instruccional / currículo', 50, 'producto', 'educacion-general'),
  ('educacion-tutor-acompanamiento', 'educacion', 'Tutor(a) / acompañamiento', 60, 'producto', 'educacion-general'),
  ('educacion-investigador-educativo', 'educacion', 'Investigación educativa', 70, 'producto', 'educacion-general'),
  ('educacion-bibliotecario-educativo', 'educacion', 'Bibliotecario(a) / recursos de aprendizaje', 80, 'producto', 'educacion-general'),
  ('educacion-especialista-lms-edtech', 'educacion', 'Especialista LMS / plataformas (Edtech)', 90, 'producto', 'educacion-general'),
  ('educacion-psicopedagogo-orientacion', 'educacion', 'Psicopedagogía / orientación', 100, 'producto', 'educacion-general'),
  ('educacion-gerente-formacion-corporativa', 'educacion', 'Gerente formación corporativa (L&D)', 110, 'producto', 'educacion-general'),
  ('educacion-facilitador-trainer', 'educacion', 'Facilitador(a) / trainer', 120, 'producto', 'educacion-general'),
  ('educacion-evaluacion-acreditacion', 'educacion', 'Evaluación y acreditación', 130, 'producto', 'educacion-general'),
  ('educacion-instructor-idiomas', 'educacion', 'Instructor(a) de idiomas', 140, 'producto', 'educacion-general'),
  ('educacion-direccion-artistica-educativa', 'educacion', 'Dirección artística educativa', 150, 'producto', 'educacion-general'),
  ('educacion-admisiones-registro', 'educacion', 'Admisiones y registro académico', 160, 'producto', 'educacion-general'),
  ('educacion-product-manager-edtech', 'educacion', 'Product manager Edtech', 170, 'producto', 'educacion-general'),
  ('educacion-marketing-comunicacion-educativa', 'educacion', 'Marketing y comunicación educativa', 180, 'producto', 'educacion-general'),
  ('educacion-movilidad-becas', 'educacion', 'Movilidad, becas e intercambios', 190, 'producto', 'educacion-general'),
  ('finanzas-fintech-analista-financiero', 'finanzas-fintech', 'Analista financiero', 10, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-contador', 'finanzas-fintech', 'Contador(a)', 20, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-auditor', 'finanzas-fintech', 'Auditor(a)', 30, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-tesoreria', 'finanzas-fintech', 'Tesorería / cash management', 40, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-fp-a', 'finanzas-fintech', 'FP&A / planeación financiera', 50, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-risk-manager', 'finanzas-fintech', 'Riesgos (risk manager)', 60, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-compliance-financiero', 'finanzas-fintech', 'Compliance financiero', 70, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-investment-banking', 'finanzas-fintech', 'Investment banking / corporate finance', 80, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-portfolio-asset-manager', 'finanzas-fintech', 'Portfolio / asset manager', 90, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-private-banker', 'finanzas-fintech', 'Private banker / wealth', 100, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-actuario', 'finanzas-fintech', 'Actuario(a)', 110, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-fiscalista', 'finanzas-fintech', 'Fiscalista', 120, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-trader', 'finanzas-fintech', 'Trader / mercados', 130, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-credito-analyst', 'finanzas-fintech', 'Crédito / scoring', 140, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-product-manager-fintech', 'finanzas-fintech', 'Product manager fintech', 150, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-cfo-director-financiero', 'finanzas-fintech', 'CFO / director(a) financiero(a)', 160, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-controller', 'finanzas-fintech', 'Controller', 170, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-relationship-manager-banca', 'finanzas-fintech', 'Relationship manager banca', 180, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-operaciones-back-office', 'finanzas-fintech', 'Operaciones / middle y back office', 190, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-data-cuant-finanzas', 'finanzas-fintech', 'Data / cuant en finanzas', 200, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-venture-analyst', 'finanzas-fintech', 'Venture / VC analyst', 210, 'negocio', 'finanzas-fintech-general'),
  ('finanzas-fintech-ma-advisory', 'finanzas-fintech', 'M&A / advisory', 220, 'negocio', 'finanzas-fintech-general'),
  ('entretenimiento-medios-productor-audiovisual', 'entretenimiento-medios', 'Productor(a) audiovisual / evento', 10, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-director-creativo', 'entretenimiento-medios', 'Director(a) creativo(a)', 20, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-director-arte-medios', 'entretenimiento-medios', 'Director(a) de arte', 30, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-editor-post', 'entretenimiento-medios', 'Editor(a) / postproducción', 40, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-sonidista', 'entretenimiento-medios', 'Sonido / diseño sonoro', 50, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-guionista', 'entretenimiento-medios', 'Guionista / IP', 60, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-manager-talento', 'entretenimiento-medios', 'Manager / booker de talento', 70, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-distribucion-adquisiciones', 'entretenimiento-medios', 'Distribución / adquisiciones', 80, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-community-social-fans', 'entretenimiento-medios', 'Community / social de fans', 90, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-host-presentador', 'entretenimiento-medios', 'Presentador(a) / host', 100, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-fotografo-editorial', 'entretenimiento-medios', 'Fotografía editorial', 110, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-motion-designer', 'entretenimiento-medios', 'Motion / motion designer', 120, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-game-developer', 'entretenimiento-medios', 'Developer videojuegos', 130, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-game-designer', 'entretenimiento-medios', 'Game designer', 140, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-esports-manager', 'entretenimiento-medios', 'Esports / competitivo', 150, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-marketing-contenidos', 'entretenimiento-medios', 'Marketing de contenidos', 160, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-brand-partnerships', 'entretenimiento-medios', 'Alianzas y branded content', 170, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-legal-clearance', 'entretenimiento-medios', 'Legal / clearance', 180, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-operaciones-venue-gira', 'entretenimiento-medios', 'Operaciones de venue / gira', 190, 'producto', 'entretenimiento-medios-general'),
  ('entretenimiento-medios-insights-audiencia', 'entretenimiento-medios', 'Data / insights de audiencia', 200, 'producto', 'entretenimiento-medios-general'),
  ('artes-diseno-creativo-disenador-grafico', 'artes-diseno-creativo', 'Diseñador(a) gráfico(a)', 10, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-disenador-producto', 'artes-diseno-creativo', 'Diseñador(a) de producto', 20, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-ilustrador', 'artes-diseno-creativo', 'Ilustrador(a)', 30, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-director-arte', 'artes-diseno-creativo', 'Dirección de arte', 40, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-fotografo-artistico', 'artes-diseno-creativo', 'Fotógrafo(a)', 50, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-artesano-maker', 'artes-diseno-creativo', 'Artesano(a) / maker', 60, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-curador', 'artes-diseno-creativo', 'Curador(a)', 70, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-interiorista', 'artes-diseno-creativo', 'Interiorismo', 80, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-moda-patronaje', 'artes-diseno-creativo', 'Moda / patronaje / confección', 90, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-orfebre-joyero', 'artes-diseno-creativo', 'Joyería / orfebrería', 100, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-ceramista', 'artes-diseno-creativo', 'Cerámica / materiales', 110, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-tipografia-branding', 'artes-diseno-creativo', 'Tipografía / branding', 120, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-motion-arte', 'artes-diseno-creativo', 'Motion / arte digital', 130, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-artista-escenico', 'artes-diseno-creativo', 'Artista escénico / performer', 140, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-escritor-copy', 'artes-diseno-creativo', 'Escritor(a) / copy creativo', 150, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-gestion-cultural', 'artes-diseno-creativo', 'Gestión cultural / producción independiente', 160, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-arquitecto', 'artes-diseno-creativo', 'Arquitecto(a)', 170, 'producto', 'artes-diseno-creativo-general'),
  ('artes-diseno-creativo-practicante-arte', 'artes-diseno-creativo', 'Estudiante / practicante arte', 180, 'producto', 'artes-diseno-creativo-general'),
  ('construccion-inmobiliario-arquitecto-proyecto', 'construccion-inmobiliario', 'Arquitecto(a) de proyecto', 10, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-ingeniero-civil', 'construccion-inmobiliario', 'Ingeniero(a) civil', 20, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-supervisor-obra', 'construccion-inmobiliario', 'Supervisor(a) / maestro de obra', 30, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-project-manager-obra', 'construccion-inmobiliario', 'Project manager construcción', 40, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-costos-presupuestos', 'construccion-inmobiliario', 'Costos / presupuestos / quantity', 50, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-seguridad-obra', 'construccion-inmobiliario', 'Seguridad e higiene en obra', 60, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-topografo', 'construccion-inmobiliario', 'Topografía / levantamientos', 70, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-bim-modelado', 'construccion-inmobiliario', 'BIM / modelado', 80, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-facility-manager', 'construccion-inmobiliario', 'Facility / asset management', 90, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-broker-inmobiliario', 'construccion-inmobiliario', 'Broker / corredor(a)', 100, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-desarrollador-inmobiliario', 'construccion-inmobiliario', 'Desarrollador(a) inmobiliario', 110, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-valuador', 'construccion-inmobiliario', 'Valuación', 120, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-urbanista', 'construccion-inmobiliario', 'Urbanismo', 130, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-mantenimiento-inmuebles', 'construccion-inmobiliario', 'Mantenimiento de inmuebles', 140, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-compras-licitaciones', 'construccion-inmobiliario', 'Compras / licitaciones', 150, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-ambiental-permisos', 'construccion-inmobiliario', 'Impacto ambiental / permisos', 160, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-interiorista-ejecutivo', 'construccion-inmobiliario', 'Interiorista ejecutivo', 170, 'operaciones', 'construccion-inmobiliario-general'),
  ('construccion-inmobiliario-legal-obra', 'construccion-inmobiliario', 'Legal obra e inmobiliario', 180, 'operaciones', 'construccion-inmobiliario-general'),
  ('manufactura-industria-gerente-planta', 'manufactura-industria', 'Gerente de planta', 10, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-supervisor-produccion', 'manufactura-industria', 'Supervisor(a) de producción', 20, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-ingeniero-procesos', 'manufactura-industria', 'Ingeniero(a) de procesos', 30, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-mantenimiento-confiabilidad', 'manufactura-industria', 'Mantenimiento / confiabilidad', 40, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-gerente-calidad', 'manufactura-industria', 'Calidad / QA planta', 50, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-supply-chain-manager', 'manufactura-industria', 'Supply chain / compras planta', 60, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-lean-mejora-continua', 'manufactura-industria', 'Lean / mejora continua', 70, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-hseq-planta', 'manufactura-industria', 'HSEQ planta', 80, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-ingeniero-automatizacion', 'manufactura-industria', 'Automatización / controles', 90, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-ingeniero-layout-planta', 'manufactura-industria', 'Layout de planta / industrial', 100, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-coordinador-logistica-almacen', 'manufactura-industria', 'Logística / almacén', 110, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-operario-tecnico-planta', 'manufactura-industria', 'Operario(a) / técnico(a) de planta', 120, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-product-manager-industrial', 'manufactura-industria', 'Product manager industrial / B2B', 130, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-ambiente-planta', 'manufactura-industria', 'Ambiente y permisos planta', 140, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-herramental', 'manufactura-industria', 'Herramental / tooling', 150, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-planeacion-mrp', 'manufactura-industria', 'Planeación / MRP', 160, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-npi-lanzamiento', 'manufactura-industria', 'NPI / lanzamiento de producto', 170, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-metrologia-lab', 'manufactura-industria', 'Metrología / lab planta', 180, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-gerente-compras', 'manufactura-industria', 'Compras estratégicas', 190, 'operaciones', 'manufactura-industria-general'),
  ('manufactura-industria-gerente-almacen-wms', 'manufactura-industria', 'Almacén / WMS', 200, 'operaciones', 'manufactura-industria-general'),
  ('agro-alimentacion-agronomo', 'agro-alimentacion', 'Agrónomo(a)', 10, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-zootecnista', 'agro-alimentacion', 'Zootecnia / ganadero técnico', 20, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-veterinario-campo', 'agro-alimentacion', 'Veterinario(a) de campo', 30, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-calidad-inocuidad-alimentos', 'agro-alimentacion', 'Calidad e inocuidad alimentaria', 40, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-i-d-alimentos', 'agro-alimentacion', 'I+D de alimentos', 50, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-produccion-planta-alimentos', 'agro-alimentacion', 'Producción / planta alimentos', 60, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-comercial-agro', 'agro-alimentacion', 'Comercial agro / trader', 70, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-extensionista', 'agro-alimentacion', 'Extensión / campo', 80, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-operaciones-restaurante', 'agro-alimentacion', 'Operaciones restaurante / F&B', 90, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-cadena-frio-logistica', 'agro-alimentacion', 'Cadena de frío / logística alimentos', 100, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-sustentabilidad-agro', 'agro-alimentacion', 'Sustentabilidad agro', 110, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-categoria-bebidas', 'agro-alimentacion', 'Bebidas / categoría', 120, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-tecnico-acuicultura', 'agro-alimentacion', 'Técnico(a) acuicultura', 130, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-compras-insumos', 'agro-alimentacion', 'Compras de insumos', 140, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-marketing-marca-alimentos', 'agro-alimentacion', 'Marketing marca alimentos', 150, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-direccion-agrifood', 'agro-alimentacion', 'Dirección / fundador(a) agrifood', 160, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-data-precision-agro', 'agro-alimentacion', 'Data / precision ag', 170, 'operaciones', 'agro-alimentacion-general'),
  ('agro-alimentacion-regulatorio-alimentos', 'agro-alimentacion', 'Regulatorio etiquetado / importación', 180, 'operaciones', 'agro-alimentacion-general'),
  ('gobierno-sector-publico-servidor-publico-operativo', 'gobierno-sector-publico', 'Servidor(a) público(a) operativo(a)', 10, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-directivo-publico', 'gobierno-sector-publico', 'Directivo(a) público(a)', 20, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-analista-politica-publica', 'gobierno-sector-publico', 'Analista de políticas públicas', 30, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-compras-publicas', 'gobierno-sector-publico', 'Compras públicas', 40, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-transparencia-datos', 'gobierno-sector-publico', 'Transparencia y datos abiertos', 50, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-urbanismo-publico', 'gobierno-sector-publico', 'Planeación urbana pública', 60, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-cooperacion-internacional', 'gobierno-sector-publico', 'Cooperación internacional', 70, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-seguridad-ciudadana-op', 'gobierno-sector-publico', 'Seguridad ciudadana (operativo)', 80, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-procuracion-justicia', 'gobierno-sector-publico', 'Procuración / justicia', 90, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-trabajo-social-programas', 'gobierno-sector-publico', 'Trabajo social / programas', 100, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-comunicacion-social', 'gobierno-sector-publico', 'Comunicación social / prensa', 110, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-project-manager-obra-publica', 'gobierno-sector-publico', 'Gestión de obra pública', 120, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-regulador-sectorial', 'gobierno-sector-publico', 'Regulación sectorial', 130, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-hacienda-publica', 'gobierno-sector-publico', 'Hacienda / finanzas públicas', 140, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-innovacion-gobierno', 'gobierno-sector-publico', 'Innovación / laboratorio público', 150, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-enlace-municipal', 'gobierno-sector-publico', 'Enlace municipal / territorial', 160, 'negocio', 'gobierno-sector-publico-general'),
  ('gobierno-sector-publico-consultor-sector-publico', 'gobierno-sector-publico', 'Consultor(a) sector público', 170, 'negocio', 'gobierno-sector-publico-general'),
  ('turismo-hospitalidad-gerente-hotel-resort', 'turismo-hospitalidad', 'Gerente general hotel / resort', 10, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-revenue-front-office', 'turismo-hospitalidad', 'Revenue / front office', 20, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-housekeeping', 'turismo-hospitalidad', 'Housekeeping / habitaciones', 30, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-director-f-b', 'turismo-hospitalidad', 'Director(a) F&B', 40, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-chef', 'turismo-hospitalidad', 'Chef / cocina', 50, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-sommelier-bar', 'turismo-hospitalidad', 'Sommelier / bar manager', 60, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-guia-turistico', 'turismo-hospitalidad', 'Guía turístico(a)', 70, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-agente-viajes', 'turismo-hospitalidad', 'Agente / planner viajes', 80, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-event-manager-mice', 'turismo-hospitalidad', 'Eventos MICE', 90, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-producto-experiencia-destino', 'turismo-hospitalidad', 'Experiencias / producto destino', 100, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-operaciones-aerolinea', 'turismo-hospitalidad', 'Operaciones aerolíneas / aeropuerto', 110, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-cruceros-hospitality', 'turismo-hospitalidad', 'Cruceros / hospitality barco', 120, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-marketing-destino', 'turismo-hospitalidad', 'Marketing de destino / DMO', 130, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-community-turismo', 'turismo-hospitalidad', 'Community / UGC viajes', 140, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-gerente-spa-wellness', 'turismo-hospitalidad', 'Spa / wellness turístico', 150, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-ecommerce-ota', 'turismo-hospitalidad', 'E‑commerce / OTA producto', 160, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-concierge-guest', 'turismo-hospitalidad', 'Concierge / guest relations', 170, 'negocio', 'turismo-hospitalidad-general'),
  ('turismo-hospitalidad-fundador-pyme-turismo', 'turismo-hospitalidad', 'Fundador(a) / director(a) PYME turismo', 180, 'negocio', 'turismo-hospitalidad-general'),
  ('energia-sustentabilidad-ingeniero-renovables', 'energia-sustentabilidad', 'Ingeniero(a) renovables', 10, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-ingeniero-ambiental', 'energia-sustentabilidad', 'Ingeniero(a) ambiental', 20, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-project-manager-energia', 'energia-sustentabilidad', 'PM proyectos energía / infra', 30, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-geotecnico-campo', 'energia-sustentabilidad', 'Geología / campo oil & gas', 40, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-hseq-ambiental', 'energia-sustentabilidad', 'HSEQ ambiental', 50, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-carbono-mrv', 'energia-sustentabilidad', 'Mercados de carbono / MRV', 60, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-energy-trader', 'energia-sustentabilidad', 'Trader energía', 70, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-operacion-red-utility', 'energia-sustentabilidad', 'Operación red / utility', 80, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-sostenibilidad-esg', 'energia-sustentabilidad', 'Sostenibilidad corporativa / ESG', 90, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-eficiencia-energetica', 'energia-sustentabilidad', 'Eficiencia energética / modelado', 100, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-residuos-economia-circular', 'energia-sustentabilidad', 'Residuos / economía circular', 110, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-hidrologia-agua', 'energia-sustentabilidad', 'Hidrología / agua', 120, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-tecnico-nuclear-servicios', 'energia-sustentabilidad', 'Técnico(a) nuclear (servicios)', 130, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-innovacion-cleantech', 'energia-sustentabilidad', 'Innovación cleantech', 140, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-legal-energia', 'energia-sustentabilidad', 'Legal energía / regulación', 150, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-project-finance-infra', 'energia-sustentabilidad', 'Project finance infra energía', 160, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-om-plantas', 'energia-sustentabilidad', 'O&M plantas', 170, 'ciencia', 'energia-sustentabilidad-general'),
  ('energia-sustentabilidad-fundador-energy-startup', 'energia-sustentabilidad', 'Fundador(a) startup energía', 180, 'ciencia', 'energia-sustentabilidad-general'),
  ('retail-comercio-gerente-tienda', 'retail-comercio', 'Gerente de tienda', 10, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-buyer-merchandising', 'retail-comercio', 'Buyer / merchandising', 20, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-planeacion-inventarios', 'retail-comercio', 'Planeación / inventarios', 30, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-gerente-ecommerce', 'retail-comercio', 'Gerente e‑commerce', 40, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-product-manager-retail', 'retail-comercio', 'Product manager retail', 50, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-supply-chain-retail', 'retail-comercio', 'Supply chain retail', 60, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-visual-merchandiser', 'retail-comercio', 'Visual merchandising', 70, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-trade-shopper', 'retail-comercio', 'Trade / shopper marketing', 80, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-crm-lealtad', 'retail-comercio', 'CRM / lealtad', 90, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-operaciones-omnicanal', 'retail-comercio', 'Operaciones omnicanal', 100, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-franquicias', 'retail-comercio', 'Franquicias', 110, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-pricing-analyst', 'retail-comercio', 'Pricing', 120, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-ultima-milla-fulfillment', 'retail-comercio', 'Última milla / fulfillment', 130, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-data-analyst-retail', 'retail-comercio', 'Data retail', 140, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-brand-manager', 'retail-comercio', 'Brand manager', 150, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-vendedor-piso', 'retail-comercio', 'Vendedor(a) / piso de tienda', 160, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-comercio-exterior-retail', 'retail-comercio', 'Comercio exterior / sourcing', 170, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-fundador-d2c', 'retail-comercio', 'Fundador(a) marca D2C', 180, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-mayoreo-cash', 'retail-comercio', 'Mayoreo / cash & carry', 190, 'negocio', 'retail-comercio-general'),
  ('retail-comercio-cx-retail', 'retail-comercio', 'Experiencia cliente / CX', 200, 'negocio', 'retail-comercio-general'),
  ('legal-consultoria-abogado-litigio', 'legal-consultoria', 'Abogado(a) litigio', 10, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-abogado-corporativo-ma', 'legal-consultoria', 'Abogado(a) corporativo / M&A', 20, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-fiscalista-abogado', 'legal-consultoria', 'Fiscalista', 30, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-abogado-laboral', 'legal-consultoria', 'Laboral', 40, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-compliance-legal', 'legal-consultoria', 'Compliance legal', 50, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-notario', 'legal-consultoria', 'Notario(a)', 60, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-consultor-estrategia', 'legal-consultoria', 'Consultor(a) de estrategia', 70, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-consultor-operaciones', 'legal-consultoria', 'Consultor(a) de operaciones', 80, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-auditor-externo', 'legal-consultoria', 'Auditor(a) externo', 90, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-reclutador-ta', 'legal-consultoria', 'Reclutador(a) / TA', 100, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-hr-business-partner', 'legal-consultoria', 'HR business partner', 110, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-gerente-rrhh', 'legal-consultoria', 'Gerente RR.HH.', 120, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-compensaciones-beneficios', 'legal-consultoria', 'Compensaciones / nómina', 130, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-people-analytics-hris', 'legal-consultoria', 'People analytics / HRIS', 140, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-coach-ejecutivo', 'legal-consultoria', 'Coach ejecutivo', 150, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-gestion-cambio-ocm', 'legal-consultoria', 'Gestión del cambio (OCM)', 160, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-abogado-pi', 'legal-consultoria', 'Propiedad intelectual / marcas', 170, 'negocio', 'legal-consultoria-general'),
  ('legal-consultoria-paralegal-legal-ops', 'legal-consultoria', 'Paralegal / legal operations', 180, 'negocio', 'legal-consultoria-general'),
  ('deporte-bienestar-entrenador-personal', 'deporte-bienestar', 'Entrenador(a) personal / fitness', 10, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-nutricionista-deportivo', 'deporte-bienestar', 'Nutrición deportiva', 20, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-fisioterapeuta-deporte', 'deporte-bienestar', 'Fisioterapia deportiva', 30, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-medico-deportivo', 'deporte-bienestar', 'Médico(a) deportivo(a)', 40, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-preparador-fisico', 'deporte-bienestar', 'Preparador(a) físico(a)', 50, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-director-tecnico-deportivo', 'deporte-bienestar', 'Director(a) técnico(a) deportivo', 60, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-psicologo-deporte', 'deporte-bienestar', 'Psicología deportiva', 70, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-gestor-club-liga', 'deporte-bienestar', 'Gestión club / liga', 80, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-instructor-grupal', 'deporte-bienestar', 'Instructor(a) grupal / boutique', 90, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-instructor-yoga-pilates', 'deporte-bienestar', 'Yoga / pilates / mind-body', 100, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-community-wellness', 'deporte-bienestar', 'Community wellness / retención', 110, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-marketing-deportivo', 'deporte-bienestar', 'Marketing deportivo', 120, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-operaciones-gimnasio', 'deporte-bienestar', 'Operaciones gimnasio', 130, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-product-manager-wellness-app', 'deporte-bienestar', 'Product manager wellness / app', 140, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-data-wearables-rendimiento', 'deporte-bienestar', 'Data wearables / rendimiento', 150, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-terapia-manual-masaje', 'deporte-bienestar', 'Masaje / terapia manual', 160, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-fundador-wellness-startup', 'deporte-bienestar', 'Fundador(a) wellness / startup', 170, 'producto', 'deporte-bienestar-general'),
  ('deporte-bienestar-readaptacion-lesion', 'deporte-bienestar', 'Readaptación / lesión', 180, 'producto', 'deporte-bienestar-general')
;
-- Recorta arrays a slugs válidos (máx. 3)
UPDATE public.profiles p
SET expertise_slugs = COALESCE((
  SELECT array_agg(e ORDER BY n)
  FROM (
    SELECT u.e AS e, u.n AS n
    FROM unnest(COALESCE(p.expertise_slugs, '{}')) WITH ORDINALITY AS u(e,n)
    INNER JOIN public.expertise_catalog c ON c.slug = u.e
    ORDER BY n
    LIMIT 3
  ) s
), '{}');

UPDATE public.searches s
SET expertise_slugs = COALESCE((
  SELECT array_agg(e ORDER BY n)
  FROM (
    SELECT u.e AS e, u.n AS n
    FROM unnest(COALESCE(s.expertise_slugs, '{}')) WITH ORDINALITY AS u(e,n)
    INNER JOIN public.expertise_catalog c ON c.slug = u.e
    ORDER BY n
    LIMIT 3
  ) s2
), '{}');

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_expertise_slugs_max5;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_expertise_slugs_max3
  CHECK (array_length(expertise_slugs, 1) IS NULL OR array_length(expertise_slugs, 1) <= 3);

ALTER TABLE public.searches DROP CONSTRAINT IF EXISTS searches_expertise_slugs_max5;
ALTER TABLE public.searches ADD CONSTRAINT searches_expertise_slugs_max3
  CHECK (array_length(expertise_slugs, 1) IS NULL OR array_length(expertise_slugs, 1) <= 3);

COMMENT ON COLUMN public.profiles.expertise_slugs IS 'Hasta 3 roles (expertise_catalog) bajo primary_industry_slug.';
COMMENT ON COLUMN public.searches.expertise_slugs IS 'Hasta 3 roles buscados bajo primary_industry_slug.';

COMMIT;

