-- Verticales adicionales (3ª ampliación, ~10 por industria). Sincronizado con lib/leaf-catalog.ts (VERTICAL_ROWS).
-- Idempotente: INSERT industries_catalog + industry_verticals ON CONFLICT DO UPDATE.

INSERT INTO public.industries_catalog (slug, name, sort_order, parent_slug) VALUES
  ('capital-riesgo-venture-debt', 'Capital de riesgo y venture debt', 270, 'finanzas-fintech'),
  ('embedded-finance-b2b', 'Embedded finance y pagos B2B', 275, 'finanzas-fintech'),
  ('fx-hedging-global', 'FX, cobertura y tesorería internacional', 280, 'finanzas-fintech'),
  ('planeacion-patrimonial-sucesoria', 'Planeación patrimonial y sucesoria', 285, 'finanzas-fintech'),
  ('consolidacion-reporting-ifrs', 'Consolidación y reporting financiero (IFRS)', 290, 'finanzas-fintech'),
  ('activos-improductivos-npl', 'NPL, activos improductivos y workout', 295, 'finanzas-fintech'),
  ('custodia-valores-post-trade', 'Custodia, clearing y post‑trading', 300, 'finanzas-fintech'),
  ('seguros-corporativos-pyme', 'Seguros corporativos y ramos especializados', 305, 'finanzas-fintech'),
  ('core-banking-tech-proveedores', 'Core banking y plataformas financieras (proveedores)', 310, 'finanzas-fintech'),
  ('spinouts-corporate-venturing', 'Corporate venturing y spinouts financieros', 315, 'finanzas-fintech'),
  ('atencion-primaria-comunitaria', 'Atención primaria y medicina comunitaria', 325, 'salud-biotech'),
  ('urgencias-hospitalarias', 'Urgencias y cuidados críticos hospitalarios', 330, 'salud-biotech'),
  ('medicina-deportiva-rehabilitacion', 'Medicina deportiva y readaptación clínica', 335, 'salud-biotech'),
  ('genomica-terapias-avanzadas', 'Genómica, terapias avanzadas y biofarmacéutica', 340, 'salud-biotech'),
  ('enfermeria-domiciliaria-paliativos', 'Enfermería domiciliaria y cuidados paliativos', 345, 'salud-biotech'),
  ('salud-materno-infantil-vertical', 'Salud materno infantil y neonatología', 350, 'salud-biotech'),
  ('optometria-salud-visual', 'Optometría y salud visual', 355, 'salud-biotech'),
  ('patologia-clinica-especializada', 'Patología clínica y laboratorio de alta complejidad', 360, 'salud-biotech'),
  ('logistica-suministro-hospitalario', 'Logística y suministro hospitalario (healthcare supply)', 365, 'salud-biotech'),
  ('telefarmacia-cadena-frio', 'Telefarmacia y cadena de frío farmacéutico', 370, 'salud-biotech'),
  ('preescolar-primera-infancia-edu', 'Preescolar y primera infancia educativa', 310, 'educacion'),
  ('stem-robotica-maker', 'STEM, robótica y makerspaces', 315, 'educacion'),
  ('coaching-certificaciones-profesionales', 'Coaching y certificaciones profesionales reguladas', 320, 'educacion'),
  ('universidad-corporativa-academy', 'Universidad corporativa y business academy', 325, 'educacion'),
  ('editorial-educativa-contenidos', 'Editorial educativa y contenidos curriculares', 330, 'educacion'),
  ('becas-financiamiento-estudiantil', 'Becas y financiamiento estudiantil', 335, 'educacion'),
  ('internacionalizacion-educativa', 'Internacionalización y alianzas académicas', 340, 'educacion'),
  ('evaluacion-online-proctoring', 'Evaluación digital y proctoring', 345, 'educacion'),
  ('desarrollo-docente-continua', 'Desarrollo docente y formación del profesorado', 350, 'educacion'),
  ('operaciones-campus-servicios', 'Operaciones de campus y servicios estudiantiles', 355, 'educacion'),
  ('api-management-integraciones', 'API management e integraciones empresariales', 900, 'tecnologia-ia'),
  ('edge-computing-industrial', 'Edge computing y planta conectada', 905, 'tecnologia-ia'),
  ('pentesting-red-team', 'Pentesting, red team y evaluación de seguridad', 910, 'tecnologia-ia'),
  ('observabilidad-apm', 'Observabilidad, APM y confiabilidad de plataformas', 915, 'tecnologia-ia'),
  ('bi-visualizacion-enterprise', 'BI, visualización y analítica enterprise', 920, 'tecnologia-ia'),
  ('erp-crm-implementacion', 'Implementación ERP, CRM y partners de sistema', 925, 'tecnologia-ia'),
  ('multicloud-finops', 'Multicloud, FinOps y optimización de nube', 930, 'tecnologia-ia'),
  ('low-code-bpm-orquestacion', 'Low‑code, BPM y orquestación de procesos', 935, 'tecnologia-ia'),
  ('automatizacion-rpa', 'Automatización RPA e hiperautomatización', 940, 'tecnologia-ia'),
  ('semiconductor-fabless-ip', 'Semiconductores, IP cores y fabless', 945, 'tecnologia-ia'),
  ('privacidad-datos-sector-publico', 'Protección de datos y privacidad en el sector público', 285, 'gobierno-sector-publico'),
  ('catastro-catastral-registro', 'Catastro, registro y ordenamiento territorial', 290, 'gobierno-sector-publico'),
  ('archivos-nacionales-documentacion', 'Archivos nacionales y gestión documental pública', 295, 'gobierno-sector-publico'),
  ('identidad-digital-ciudadania', 'Identidad digital y trámites de ciudadanía', 300, 'gobierno-sector-publico'),
  ('cultura-artes-politica-publica', 'Cultura, artes y políticas culturales públicas', 305, 'gobierno-sector-publico'),
  ('ciencia-tecnologia-politica-innovacion', 'CTI, innovación pública y laboratorios de gobierno', 310, 'gobierno-sector-publico'),
  ('adquisiciones-defensa-industrial', 'Adquisiciones de defensa e industria estratégica', 315, 'gobierno-sector-publico'),
  ('transicion-justa-energia-publica', 'Transición energética justa (enfoque público)', 320, 'gobierno-sector-publico'),
  ('estadistica-oficial-encuestas', 'Estadística oficial, censos y encuestas', 325, 'gobierno-sector-publico'),
  ('migracion-consular-servicios', 'Migración, consulados y servicios en frontera', 330, 'gobierno-sector-publico'),
  ('centros-comerciales-experiencia', 'Centros comerciales y experiencia de shopping', 930, 'retail-comercio'),
  ('retail-automotriz-posventa', 'Retail automotriz y posventa', 935, 'retail-comercio'),
  ('farmacia-parafarmacia-retail', 'Farmacia, parafarmacia y dermocosmética en retail', 940, 'retail-comercio'),
  ('pet-care-retail', 'Pet care, alimento y accesorios para mascotas', 945, 'retail-comercio'),
  ('hogar-muebles-decoracion', 'Hogar, muebles y decoración', 950, 'retail-comercio'),
  ('deportes-outdoor-retail', 'Deportes, outdoor y lifestyle activo', 955, 'retail-comercio'),
  ('optica-audio-retail', 'Óptica, audio y salud en retail', 960, 'retail-comercio'),
  ('b2b-marketplace-mayoreo-digital', 'B2B marketplace y mayoreo digital', 965, 'retail-comercio'),
  ('loss-prevention-seguridad-retail', 'Loss prevention y seguridad en tienda', 970, 'retail-comercio'),
  ('libreria-papeleria-cultura-retail', 'Librería, papelería y cultura en retail', 975, 'retail-comercio'),
  ('standup-comedy-clubes', 'Stand‑up, comedia en vivo y clubes', 910, 'entretenimiento-medios'),
  ('venues-conciertos-en-vivo', 'Venues, conciertos y música en vivo', 915, 'entretenimiento-medios'),
  ('management-artistico-booking', 'Management artístico y booking', 920, 'entretenimiento-medios'),
  ('sync-licencias-musica-publicidad', 'Sync, licencias musicales y publicidad', 925, 'entretenimiento-medios'),
  ('vfx-post-animation-studios', 'VFX, posproducción y estudios de animación', 930, 'entretenimiento-medios'),
  ('doblaje-locucion-audiobooks', 'Doblaje, locución y audiolibros', 935, 'entretenimiento-medios'),
  ('esports-franquicias-equipos', 'Franquicias y operación de equipos esports', 940, 'entretenimiento-medios'),
  ('experiencias-inmersivas-xr', 'Experiencias inmersivas XR y venue digital', 945, 'entretenimiento-medios'),
  ('film-commissions-locaciones', 'Film commissions y atracción de rodajes', 950, 'entretenimiento-medios'),
  ('distribucion-exhibicion-audiovisual', 'Distribución y exhibición audiovisual', 955, 'entretenimiento-medios'),
  ('caligrafia-tipografia-edicion', 'Caligrafía, tipografía y edición gráfica', 900, 'artes-diseno-creativo'),
  ('curaduria-exposiciones-temporales', 'Curaduría y exposiciones temporales', 905, 'artes-diseno-creativo'),
  ('arte-urbano-intervencion-publica', 'Arte urbano e intervención en espacio público', 910, 'artes-diseno-creativo'),
  ('talleres-arte-comunitario', 'Talleres, residencias y arte comunitario', 915, 'artes-diseno-creativo'),
  ('fotografia-producto-ecommerce', 'Fotografía de producto y e‑commerce visual', 920, 'artes-diseno-creativo'),
  ('joyeria-orfebreria-contemporanea', 'Joyería y orfebrería contemporánea', 925, 'artes-diseno-creativo'),
  ('ceramica-artistica-mesa', 'Cerámica artística y diseño de mesa', 930, 'artes-diseno-creativo'),
  ('performance-arte-accion', 'Performance y arte de acción', 935, 'artes-diseno-creativo'),
  ('comic-ilustrado-narrativa-grafica', 'Cómic, novela gráfica e ilustración editorial', 940, 'artes-diseno-creativo'),
  ('arte-digital-experimental', 'Arte digital experimental y nuevos medios', 945, 'artes-diseno-creativo'),
  ('restauracion-patrimonio-edificado', 'Restauración de patrimonio edificado', 265, 'construccion-inmobiliario'),
  ('infraestructura-deportiva-publica', 'Infraestructura deportiva y espacios públicos', 270, 'construccion-inmobiliario'),
  ('vivienda-renta-servicing', 'Vivienda en renta, multifamily y servicing', 275, 'construccion-inmobiliario'),
  ('naves-industriales-logistica', 'Naves industriales y desarrollo logístico', 280, 'construccion-inmobiliario'),
  ('mep-climatizacion-obra', 'MEP, climatización e instalaciones en obra', 285, 'construccion-inmobiliario'),
  ('impermeabilizacion-especialidades-obra', 'Impermeabilización y especialidades de obra', 290, 'construccion-inmobiliario'),
  ('demolicion-reciclaje-escombro', 'Demolición selectiva y reciclaje de escombros', 295, 'construccion-inmobiliario'),
  ('geotecnia-cimentaciones', 'Geotecnia y cimentaciones especiales', 300, 'construccion-inmobiliario'),
  ('seguros-obra-reclamaciones', 'Seguros de obra, reclamaciones y garantías', 305, 'construccion-inmobiliario'),
  ('bim-coordinacion-vdc-obra', 'BIM, coordinación multidisciplinaria y VDC en obra', 310, 'construccion-inmobiliario'),
  ('textil-confeccion-industrial', 'Textil, confección y moda industrial', 930, 'manufactura-industria'),
  ('muebleria-madera-industrial', 'Mueblería, madera y carpintería industrial', 935, 'manufactura-industria'),
  ('vidrio-ceramica-industrial', 'Vidrio, cerámica industrial y refractarios', 940, 'manufactura-industria'),
  ('papel-carton-empaque', 'Papel, cartón y empaque sostenible', 945, 'manufactura-industria'),
  ('fundicion-forja-metalurgia', 'Fundición, forja y metalurgia', 950, 'manufactura-industria'),
  ('plastico-extrusion-inyeccion', 'Plástico, extrusión e inyección industrial', 955, 'manufactura-industria'),
  ('pinturas-recubrimientos-industriales', 'Pinturas y recubrimientos industriales', 960, 'manufactura-industria'),
  ('caucho-neumaticos-componentes', 'Caucho, neumáticos y componentes poliméricos', 965, 'manufactura-industria'),
  ('cosmetica-planta-cuidado-personal', 'Cosmética y cuidado personal en planta', 970, 'manufactura-industria'),
  ('maquinaria-equipo-industrial-servicio', 'Maquinaria, equipo industrial y servicio técnico', 975, 'manufactura-industria'),
  ('nuclear-servicios-combustible', 'Servicios a centrales nucleares y ciclo del combustible', 305, 'energia-sustentabilidad'),
  ('mineria-cierre-post-mineria', 'Cierre de minas y rehabilitación post‑minería', 310, 'energia-sustentabilidad'),
  ('eficiencia-energetica-edificaciones', 'Eficiencia energética en edificaciones', 315, 'energia-sustentabilidad'),
  ('demanda-respuesta-grid-flexibility', 'Gestión de demanda y flexibilidad de red', 320, 'energia-sustentabilidad'),
  ('mercado-mayorista-electrico', 'Mercado mayorista y comercialización eléctrica', 325, 'energia-sustentabilidad'),
  ('auditorias-certificacion-energetica', 'Auditorías y certificación energética / normativa', 330, 'energia-sustentabilidad'),
  ('agrivoltaica-energia-suelo', 'Agrivoltaica y uso dual del suelo', 335, 'energia-sustentabilidad'),
  ('baterias-segunda-vida-reciclaje', 'Baterías, segunda vida y reciclaje de acumulación', 340, 'energia-sustentabilidad'),
  ('compliance-ambiental-operacion', 'Compliance ambiental de operación industrial', 345, 'energia-sustentabilidad'),
  ('infraestructura-recarga-movilidad-electrica', 'Infraestructura de recarga y hubs de movilidad eléctrica', 350, 'energia-sustentabilidad'),
  ('agricultura-regenerativa-suelo', 'Agricultura regenerativa y salud del suelo', 305, 'agro-alimentacion'),
  ('riego-precision-agua', 'Riego tecnificado y gestión hídrica agrícola', 310, 'agro-alimentacion'),
  ('bioinsumos-biocontrol', 'Bioinsumos, biocontrol y agricultura biológica', 315, 'agro-alimentacion'),
  ('fruticultura-especializada', 'Fruticultura de especialidad y berries', 320, 'agro-alimentacion'),
  ('cafe-cacao-origen', 'Café, cacao y orígenes de altitud', 325, 'agro-alimentacion'),
  ('lacteos-procesamiento-rural', 'Lácteos y queserías de escala regional', 330, 'agro-alimentacion'),
  ('carnicos-rastro-transformacion', 'Cárnicos, rastro y transformación local', 335, 'agro-alimentacion'),
  ('food-safety-auditorias-terceros', 'Food safety y auditorías de tercera parte', 340, 'agro-alimentacion'),
  ('packaging-alimentos-sostenible', 'Packaging alimentario y materiales sostenibles', 345, 'agro-alimentacion'),
  ('agricultura-invernadero-controlado', 'Agricultura protegida, invernadero y cultivo controlado', 350, 'agro-alimentacion'),
  ('guias-interpretacion-idiomas', 'Guías, interpretación e idiomas especializados', 335, 'turismo-hospitalidad'),
  ('turismo-accesible-inclusivo', 'Turismo accesible e inclusivo', 340, 'turismo-hospitalidad'),
  ('turismo-lgbtq-segmento', 'Turismo LGBTQ+ friendly y segmentos', 345, 'turismo-hospitalidad'),
  ('turismo-educativo-workshops', 'Turismo educativo, workshops y residencias', 350, 'turismo-hospitalidad'),
  ('transporte-turistico-terrestre', 'Transporte turístico terrestre y traslados', 355, 'turismo-hospitalidad'),
  ('asistencia-viajero-insurtech', 'Asistencia al viajero y seguros turísticos', 360, 'turismo-hospitalidad'),
  ('revenue-hotelero-herramientas', 'Revenue management y distribución hotelera', 365, 'turismo-hospitalidad'),
  ('turismo-marino-buceo-nautico', 'Turismo marino, buceo y náutica', 370, 'turismo-hospitalidad'),
  ('turismo-rural-comunitario', 'Turismo rural, comunitario y experiencias locales', 375, 'turismo-hospitalidad'),
  ('enoturismo-rutas-gastronomicas', 'Enoturismo, destilados y rutas gastronómicas', 380, 'turismo-hospitalidad'),
  ('compliance-penal-empresarial', 'Compliance penal y gobierno corporativo', 285, 'legal-consultoria'),
  ('proteccion-consumidor-b2c', 'Protección al consumidor y litigio B2C', 290, 'legal-consultoria'),
  ('competencia-antitrust', 'Competencia económica y antitrust', 295, 'legal-consultoria'),
  ('privacidad-dpo-externo', 'Privacidad, DPO externo y datos', 300, 'legal-consultoria'),
  ('contratacion-saas-tech-legal', 'Contratación tecnológica, SaaS y licencias', 305, 'legal-consultoria'),
  ('laboral-sindical-colectivo', 'Laboral sindical y negociación colectiva', 310, 'legal-consultoria'),
  ('legal-inmobiliario-transaccional', 'Legal inmobiliario y transaccional', 315, 'legal-consultoria'),
  ('venture-startups-cap-table', 'Venture, startups y cap table', 320, 'legal-consultoria'),
  ('propiedad-intelectual-patentes', 'Propiedad intelectual y patentes', 325, 'legal-consultoria'),
  ('mediacion-arbitraje-comercial', 'Mediación y arbitraje comercial', 330, 'legal-consultoria'),
  ('padel-tenis-clubes-raqueta', 'Pádel, tenis y clubes de raqueta', 285, 'deporte-bienestar'),
  ('yoga-pilates-mind-body-studios', 'Yoga, pilates y estudios mind-body', 290, 'deporte-bienestar'),
  ('crossfit-hiit-boxes-funcional', 'CrossFit, HIIT y entrenamiento funcional en box', 295, 'deporte-bienestar'),
  ('natacion-deportes-acuaticos-clubes', 'Natación, deportes acuáticos y clubes', 300, 'deporte-bienestar'),
  ('ciclismo-running-triatlon-comunidades', 'Ciclismo, running y triatlón (comunidades y eventos)', 305, 'deporte-bienestar'),
  ('artes-marciales-deportes-combate', 'Artes marciales y deportes de combate', 310, 'deporte-bienestar'),
  ('deportes-invierno-montana-outdoor', 'Deportes de invierno y outdoor de montaña', 315, 'deporte-bienestar'),
  ('esports-performance-comunidad', 'Esports, rendimiento y comunidad competitiva', 320, 'deporte-bienestar'),
  ('spa-termal-wellness-destination', 'Spa, termalismo y wellness destination', 325, 'deporte-bienestar'),
  ('suplementos-nutricion-fitness-comercio', 'Suplementos y nutrición fitness (retail y omnicanal)', 330, 'deporte-bienestar')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order,
  parent_slug = EXCLUDED.parent_slug;

INSERT INTO public.industry_verticals (slug, industry_slug, label, sort_order, maps_to)
SELECT c.slug, c.parent_slug, c.name, COALESCE(c.sort_order, 0) + 100, i.maps_to
FROM public.industries_catalog c
INNER JOIN public.industries i ON i.slug = c.parent_slug
WHERE c.slug IN (
  'capital-riesgo-venture-debt', 'embedded-finance-b2b', 'fx-hedging-global', 'planeacion-patrimonial-sucesoria', 'consolidacion-reporting-ifrs',
  'activos-improductivos-npl', 'custodia-valores-post-trade', 'seguros-corporativos-pyme', 'core-banking-tech-proveedores', 'spinouts-corporate-venturing',
  'atencion-primaria-comunitaria', 'urgencias-hospitalarias', 'medicina-deportiva-rehabilitacion', 'genomica-terapias-avanzadas', 'enfermeria-domiciliaria-paliativos',
  'salud-materno-infantil-vertical', 'optometria-salud-visual', 'patologia-clinica-especializada', 'logistica-suministro-hospitalario', 'telefarmacia-cadena-frio',
  'preescolar-primera-infancia-edu', 'stem-robotica-maker', 'coaching-certificaciones-profesionales', 'universidad-corporativa-academy', 'editorial-educativa-contenidos',
  'becas-financiamiento-estudiantil', 'internacionalizacion-educativa', 'evaluacion-online-proctoring', 'desarrollo-docente-continua', 'operaciones-campus-servicios',
  'api-management-integraciones', 'edge-computing-industrial', 'pentesting-red-team', 'observabilidad-apm', 'bi-visualizacion-enterprise',
  'erp-crm-implementacion', 'multicloud-finops', 'low-code-bpm-orquestacion', 'automatizacion-rpa', 'semiconductor-fabless-ip',
  'privacidad-datos-sector-publico', 'catastro-catastral-registro', 'archivos-nacionales-documentacion', 'identidad-digital-ciudadania', 'cultura-artes-politica-publica',
  'ciencia-tecnologia-politica-innovacion', 'adquisiciones-defensa-industrial', 'transicion-justa-energia-publica', 'estadistica-oficial-encuestas', 'migracion-consular-servicios',
  'centros-comerciales-experiencia', 'retail-automotriz-posventa', 'farmacia-parafarmacia-retail', 'pet-care-retail', 'hogar-muebles-decoracion',
  'deportes-outdoor-retail', 'optica-audio-retail', 'b2b-marketplace-mayoreo-digital', 'loss-prevention-seguridad-retail', 'libreria-papeleria-cultura-retail',
  'standup-comedy-clubes', 'venues-conciertos-en-vivo', 'management-artistico-booking', 'sync-licencias-musica-publicidad', 'vfx-post-animation-studios',
  'doblaje-locucion-audiobooks', 'esports-franquicias-equipos', 'experiencias-inmersivas-xr', 'film-commissions-locaciones', 'distribucion-exhibicion-audiovisual',
  'caligrafia-tipografia-edicion', 'curaduria-exposiciones-temporales', 'arte-urbano-intervencion-publica', 'talleres-arte-comunitario', 'fotografia-producto-ecommerce',
  'joyeria-orfebreria-contemporanea', 'ceramica-artistica-mesa', 'performance-arte-accion', 'comic-ilustrado-narrativa-grafica', 'arte-digital-experimental',
  'restauracion-patrimonio-edificado', 'infraestructura-deportiva-publica', 'vivienda-renta-servicing', 'naves-industriales-logistica', 'mep-climatizacion-obra',
  'impermeabilizacion-especialidades-obra', 'demolicion-reciclaje-escombro', 'geotecnia-cimentaciones', 'seguros-obra-reclamaciones', 'bim-coordinacion-vdc-obra',
  'textil-confeccion-industrial', 'muebleria-madera-industrial', 'vidrio-ceramica-industrial', 'papel-carton-empaque', 'fundicion-forja-metalurgia',
  'plastico-extrusion-inyeccion', 'pinturas-recubrimientos-industriales', 'caucho-neumaticos-componentes', 'cosmetica-planta-cuidado-personal', 'maquinaria-equipo-industrial-servicio',
  'nuclear-servicios-combustible', 'mineria-cierre-post-mineria', 'eficiencia-energetica-edificaciones', 'demanda-respuesta-grid-flexibility', 'mercado-mayorista-electrico',
  'auditorias-certificacion-energetica', 'agrivoltaica-energia-suelo', 'baterias-segunda-vida-reciclaje', 'compliance-ambiental-operacion', 'infraestructura-recarga-movilidad-electrica',
  'agricultura-regenerativa-suelo', 'riego-precision-agua', 'bioinsumos-biocontrol', 'fruticultura-especializada', 'cafe-cacao-origen',
  'lacteos-procesamiento-rural', 'carnicos-rastro-transformacion', 'food-safety-auditorias-terceros', 'packaging-alimentos-sostenible', 'agricultura-invernadero-controlado',
  'guias-interpretacion-idiomas', 'turismo-accesible-inclusivo', 'turismo-lgbtq-segmento', 'turismo-educativo-workshops', 'transporte-turistico-terrestre',
  'asistencia-viajero-insurtech', 'revenue-hotelero-herramientas', 'turismo-marino-buceo-nautico', 'turismo-rural-comunitario', 'enoturismo-rutas-gastronomicas',
  'compliance-penal-empresarial', 'proteccion-consumidor-b2c', 'competencia-antitrust', 'privacidad-dpo-externo', 'contratacion-saas-tech-legal',
  'laboral-sindical-colectivo', 'legal-inmobiliario-transaccional', 'venture-startups-cap-table', 'propiedad-intelectual-patentes', 'mediacion-arbitraje-comercial',
  'padel-tenis-clubes-raqueta', 'yoga-pilates-mind-body-studios', 'crossfit-hiit-boxes-funcional', 'natacion-deportes-acuaticos-clubes', 'ciclismo-running-triatlon-comunidades',
  'artes-marciales-deportes-combate', 'deportes-invierno-montana-outdoor', 'esports-performance-comunidad', 'spa-termal-wellness-destination', 'suplementos-nutricion-fitness-comercio'
)
  AND c.parent_slug IS NOT NULL
  AND c.slug NOT IN (SELECT slug FROM public.industries)
ON CONFLICT (slug) DO UPDATE SET
  industry_slug = EXCLUDED.industry_slug,
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  maps_to = EXCLUDED.maps_to;
