-- Verticales de foco adicionales por industria (alineado con lib/profile-taxonomy.ts).
INSERT INTO public.expertise_catalog (slug, industry_slug, label, sort_order, maps_to) VALUES
  ('salud-biotech-enfermeria-y-cuidados-especializados', 'salud-biotech', 'Enfermería y cuidados especializados', 160, 'ciencia'),
  ('salud-biotech-cardiologia', 'salud-biotech', 'Cardiología', 170, 'ciencia'),
  ('salud-biotech-dermatologia', 'salud-biotech', 'Dermatología', 180, 'ciencia'),
  ('salud-biotech-pediatria', 'salud-biotech', 'Pediatría', 190, 'ciencia'),
  ('salud-biotech-inmunologia', 'salud-biotech', 'Inmunología', 200, 'ciencia'),
  ('salud-biotech-radiologia-e-imagen-medica', 'salud-biotech', 'Radiología e imagen médica', 210, 'ciencia'),
  ('salud-biotech-patologia-clinica', 'salud-biotech', 'Patología clínica', 220, 'ciencia'),
  ('salud-biotech-salud-digital-y-apps-clinicas', 'salud-biotech', 'Salud digital y apps clínicas', 230, 'ciencia'),
  ('salud-biotech-longevidad-y-medicina-antienvejecimiento', 'salud-biotech', 'Longevidad y medicina antienvejecimiento', 240, 'ciencia'),
  ('salud-biotech-odontologia', 'salud-biotech', 'Odontología', 250, 'ciencia'),
  ('salud-biotech-oftalmologia-y-optometria', 'salud-biotech', 'Oftalmología y optometría', 260, 'ciencia'),
  ('salud-biotech-medicina-veterinaria-y-one-health', 'salud-biotech', 'Medicina veterinaria y One Health', 270, 'ciencia'),
  ('salud-biotech-ensayos-clinicos-y-cro', 'salud-biotech', 'Ensayos clínicos y CRO', 280, 'ciencia'),
  ('salud-biotech-farmacovigilancia', 'salud-biotech', 'Farmacovigilancia', 290, 'ciencia'),
  ('salud-biotech-biomarcadores-y-diagnostico-avanzado', 'salud-biotech', 'Biomarcadores y diagnóstico avanzado', 300, 'ciencia'),
  ('salud-biotech-salud-materno-infantil', 'salud-biotech', 'Salud materno-infantil', 310, 'ciencia'),
  ('salud-biotech-epidemiologia', 'salud-biotech', 'Epidemiología', 320, 'ciencia'),
  ('salud-biotech-salud-ocupacional', 'salud-biotech', 'Salud ocupacional', 330, 'ciencia'),
  ('salud-biotech-terapia-fisica-y-ocupacional', 'salud-biotech', 'Terapia física y ocupacional', 340, 'ciencia'),
  ('salud-biotech-bienestar-laboral-y-salud-corporativa', 'salud-biotech', 'Bienestar laboral y salud corporativa', 350, 'ciencia'),
  ('educacion-stem-y-divulgacion-cientifica', 'educacion', 'STEM y divulgación científica', 140, 'producto'),
  ('educacion-evaluacion-y-medicion-del-aprendizaje', 'educacion', 'Evaluación y medición del aprendizaje', 150, 'producto'),
  ('educacion-curriculo-y-diseno-instruccional', 'educacion', 'Currículo y diseño instruccional', 160, 'producto'),
  ('educacion-plataformas-lms-y-contenido-digital', 'educacion', 'Plataformas LMS y contenido digital', 170, 'producto'),
  ('educacion-gestion-y-direccion-escolar', 'educacion', 'Gestión y dirección escolar', 180, 'producto'),
  ('educacion-inclusion-equidad-y-diversidad', 'educacion', 'Inclusión, equidad y diversidad', 190, 'producto'),
  ('educacion-educacion-infantil-y-primera-infancia', 'educacion', 'Educación infantil y primera infancia', 200, 'producto'),
  ('educacion-educacion-de-adultos-y-mayeb', 'educacion', 'Educación de adultos y MAYEB', 210, 'producto'),
  ('educacion-bootcamps-y-entrenamiento-intensivo', 'educacion', 'Bootcamps y entrenamiento intensivo', 220, 'producto'),
  ('educacion-comunidades-de-practica-y-aprendizaje', 'educacion', 'Comunidades de práctica y aprendizaje', 230, 'producto'),
  ('educacion-investigacion-educativa', 'educacion', 'Investigación educativa', 240, 'producto'),
  ('educacion-intercambios-y-movilidad-estudiantil', 'educacion', 'Intercambios y movilidad estudiantil', 250, 'producto'),
  ('educacion-arte-y-cultura-en-el-curriculo', 'educacion', 'Arte y cultura en el currículo', 260, 'producto'),
  ('educacion-bibliotecas-y-recursos-digitales', 'educacion', 'Bibliotecas y recursos digitales', 270, 'producto'),
  ('educacion-acreditacion-y-aseguramiento-de-calidad', 'educacion', 'Acreditación y aseguramiento de calidad', 280, 'producto'),
  ('educacion-psicologia-educativa', 'educacion', 'Psicología educativa', 290, 'producto'),
  ('educacion-comunicacion-y-relaciones-educativas', 'educacion', 'Comunicación y relaciones educativas', 300, 'producto'),
  ('educacion-alfabetizacion-y-competencias-digitales', 'educacion', 'Alfabetización y competencias digitales', 310, 'producto'),
  ('educacion-neuroeducacion', 'educacion', 'Neuroeducación', 320, 'producto'),
  ('educacion-educacion-intercultural-y-comunitaria', 'educacion', 'Educación intercultural y comunitaria', 330, 'producto'),
  ('finanzas-fintech-wealth-management', 'finanzas-fintech', 'Wealth management', 150, 'negocio'),
  ('finanzas-fintech-private-equity', 'finanzas-fintech', 'Private equity', 160, 'negocio'),
  ('finanzas-fintech-family-office', 'finanzas-fintech', 'Family office', 170, 'negocio'),
  ('finanzas-fintech-fx-tesoreria-y-mercados-globales', 'finanzas-fintech', 'FX, tesorería y mercados globales', 180, 'negocio'),
  ('finanzas-fintech-riesgo-crediticio-y-scoring', 'finanzas-fintech', 'Riesgo crediticio y scoring', 190, 'negocio'),
  ('finanzas-fintech-regtech', 'finanzas-fintech', 'RegTech', 200, 'negocio'),
  ('finanzas-fintech-aml-kyc-y-compliance-financiero', 'finanzas-fintech', 'AML, KYC y compliance financiero', 210, 'negocio'),
  ('finanzas-fintech-neobanca-y-banca-digital', 'finanzas-fintech', 'Neobanca y banca digital', 220, 'negocio'),
  ('finanzas-fintech-bnpl-y-credito-punto-de-venta', 'finanzas-fintech', 'BNPL y crédito punto de venta', 230, 'negocio'),
  ('finanzas-fintech-factoring-leasing-y-arrendamiento-financiero', 'finanzas-fintech', 'Factoring, leasing y arrendamiento financiero', 240, 'negocio'),
  ('finanzas-fintech-reaseguros-y-gestion-actuarial', 'finanzas-fintech', 'Reaseguros y gestión actuarial', 250, 'negocio'),
  ('finanzas-fintech-fp-a-y-finanzas-corporativas', 'finanzas-fintech', 'FP&A y finanzas corporativas', 260, 'negocio'),
  ('finanzas-fintech-valuacion-de-activos-y-fairness-opinion', 'finanzas-fintech', 'Valuación de activos y fairness opinion', 270, 'negocio'),
  ('finanzas-fintech-trading-cuantitativo-y-mercados', 'finanzas-fintech', 'Trading cuantitativo y mercados', 280, 'negocio'),
  ('finanzas-fintech-inversion-sostenible-y-esg', 'finanzas-fintech', 'Inversión sostenible y ESG', 290, 'negocio'),
  ('finanzas-fintech-crowdfunding-y-capital-semilla-regulado', 'finanzas-fintech', 'Crowdfunding y capital semilla regulado', 300, 'negocio'),
  ('finanzas-fintech-cobranza-y-recuperacion-de-cartera', 'finanzas-fintech', 'Cobranza y recuperación de cartera', 310, 'negocio'),
  ('finanzas-fintech-operaciones-y-middle-back-office', 'finanzas-fintech', 'Operaciones y middle/back office', 320, 'negocio'),
  ('finanzas-fintech-research-y-estrategia-de-mercados', 'finanzas-fintech', 'Research y estrategia de mercados', 330, 'negocio'),
  ('finanzas-fintech-structured-finance-y-project-finance', 'finanzas-fintech', 'Structured finance y project finance', 340, 'negocio'),
  ('entretenimiento-medios-esports-y-competicion', 'entretenimiento-medios', 'Esports y competición', 150, 'producto'),
  ('entretenimiento-medios-creators-ugc-y-comunidades-de-fans', 'entretenimiento-medios', 'Creators, UGC y comunidades de fans', 160, 'producto'),
  ('entretenimiento-medios-marketing-y-management-musical', 'entretenimiento-medios', 'Marketing y management musical', 170, 'producto'),
  ('entretenimiento-medios-festivales-giras-y-venue-management', 'entretenimiento-medios', 'Festivales, giras y venue management', 180, 'producto'),
  ('entretenimiento-medios-derechos-licencias-y-clearances', 'entretenimiento-medios', 'Derechos, licencias y clearances', 190, 'producto'),
  ('entretenimiento-medios-postproduccion-color-y-vfx', 'entretenimiento-medios', 'Postproducción, color y VFX', 200, 'producto'),
  ('entretenimiento-medios-desarrollo-de-guion-e-ip', 'entretenimiento-medios', 'Desarrollo de guion e IP', 210, 'producto'),
  ('entretenimiento-medios-casting-y-representacion-de-talento', 'entretenimiento-medios', 'Casting y representación de talento', 220, 'producto'),
  ('entretenimiento-medios-distribucion-multiplataforma', 'entretenimiento-medios', 'Distribución multiplataforma', 230, 'producto'),
  ('entretenimiento-medios-locucion-voice-over-y-audio-para-medios', 'entretenimiento-medios', 'Locución, voice-over y audio para medios', 240, 'producto'),
  ('entretenimiento-medios-fotografia-editorial-y-lifestyle', 'entretenimiento-medios', 'Fotografía editorial y lifestyle', 250, 'producto'),
  ('entretenimiento-medios-diseno-de-sonido-y-musica-para-medios', 'entretenimiento-medios', 'Diseño de sonido y música para medios', 260, 'producto'),
  ('entretenimiento-medios-experiencias-inmersivas-y-museografia', 'entretenimiento-medios', 'Experiencias inmersivas y museografía', 270, 'producto'),
  ('entretenimiento-medios-brand-integration-y-branded-content', 'entretenimiento-medios', 'Brand integration y branded content', 280, 'producto'),
  ('entretenimiento-medios-publishing-y-edicion-independiente', 'entretenimiento-medios', 'Publishing y edición independiente', 290, 'producto'),
  ('entretenimiento-medios-stand-up-comedia-en-vivo-y-clubes', 'entretenimiento-medios', 'Stand-up, comedia en vivo y clubes', 300, 'producto'),
  ('entretenimiento-medios-moda-y-contenido-lifestyle', 'entretenimiento-medios', 'Moda y contenido lifestyle', 310, 'producto'),
  ('entretenimiento-medios-no-ficcion-y-formatos-documentales', 'entretenimiento-medios', 'No ficción y formatos documentales', 320, 'producto'),
  ('entretenimiento-medios-radio-tradicional-y-syndication', 'entretenimiento-medios', 'Radio tradicional y syndication', 330, 'producto'),
  ('entretenimiento-medios-representacion-artistica-y-booking', 'entretenimiento-medios', 'Representación artística y booking', 340, 'producto'),
  ('artes-diseno-creativo-tipografia-y-lettering', 'artes-diseno-creativo', 'Tipografía y lettering', 160, 'producto'),
  ('artes-diseno-creativo-motion-graphics-y-animacion-grafica', 'artes-diseno-creativo', 'Motion graphics y animación gráfica', 170, 'producto'),
  ('artes-diseno-creativo-branding-e-identidad-visual', 'artes-diseno-creativo', 'Branding e identidad visual', 180, 'producto'),
  ('artes-diseno-creativo-packaging-y-unboxing-experience', 'artes-diseno-creativo', 'Packaging y unboxing experience', 190, 'producto'),
  ('artes-diseno-creativo-diseno-de-espacios-expositivos', 'artes-diseno-creativo', 'Diseño de espacios expositivos', 200, 'producto'),
  ('artes-diseno-creativo-arte-digital-y-cultura-web3', 'artes-diseno-creativo', 'Arte digital y cultura web3', 210, 'producto'),
  ('artes-diseno-creativo-restauracion-y-conservacion', 'artes-diseno-creativo', 'Restauración y conservación', 220, 'producto'),
  ('artes-diseno-creativo-curaduria-y-produccion-de-exposiciones', 'artes-diseno-creativo', 'Curaduría y producción de exposiciones', 230, 'producto'),
  ('artes-diseno-creativo-produccion-escenica-y-stagework', 'artes-diseno-creativo', 'Producción escénica y stagework', 240, 'producto'),
  ('artes-diseno-creativo-textiles-patronaje-y-confeccion-autoral', 'artes-diseno-creativo', 'Textiles, patronaje y confección autoral', 250, 'producto'),
  ('artes-diseno-creativo-storyboard-y-previsualizacion', 'artes-diseno-creativo', 'Storyboard y previsualización', 260, 'producto'),
  ('artes-diseno-creativo-concept-art-y-visdev', 'artes-diseno-creativo', 'Concept art y visdev', 270, 'producto'),
  ('artes-diseno-creativo-diseno-de-producto-y-prototipado', 'artes-diseno-creativo', 'Diseño de producto y prototipado', 280, 'producto'),
  ('artes-diseno-creativo-bellas-artes-academicas', 'artes-diseno-creativo', 'Bellas artes académicas', 290, 'producto'),
  ('artes-diseno-creativo-artes-mixtas-e-instalacion', 'artes-diseno-creativo', 'Artes mixtas e instalación', 300, 'producto'),
  ('artes-diseno-creativo-comisariado-independiente', 'artes-diseno-creativo', 'Comisariado independiente', 310, 'producto'),
  ('artes-diseno-creativo-diseno-regenerativo-y-materiales', 'artes-diseno-creativo', 'Diseño regenerativo y materiales', 320, 'producto'),
  ('artes-diseno-creativo-fotografia-documental-y-ensayo', 'artes-diseno-creativo', 'Fotografía documental y ensayo', 330, 'producto'),
  ('artes-diseno-creativo-videoarte-y-nuevos-medios', 'artes-diseno-creativo', 'Videoarte y nuevos medios', 340, 'producto'),
  ('artes-diseno-creativo-performance-y-arte-en-vivo', 'artes-diseno-creativo', 'Performance y arte en vivo', 350, 'producto'),
  ('construccion-inmobiliario-bim-gemelos-digitales-y-colaboracion-3d', 'construccion-inmobiliario', 'BIM, gemelos digitales y colaboración 3D', 130, 'operaciones'),
  ('construccion-inmobiliario-prefabricacion-modular-y-construccion-industrializada', 'construccion-inmobiliario', 'Prefabricación, modular y construcción industrializada', 140, 'operaciones'),
  ('construccion-inmobiliario-costos-control-presupuestal-y-quantity-surveying', 'construccion-inmobiliario', 'Costos, control presupuestal y quantity surveying', 150, 'operaciones'),
  ('construccion-inmobiliario-contratacion-licitaciones-y-claims', 'construccion-inmobiliario', 'Contratación, licitaciones y claims', 160, 'operaciones'),
  ('construccion-inmobiliario-seguridad-higiene-y-medio-ambiente-en-obra', 'construccion-inmobiliario', 'Seguridad, higiene y medio ambiente en obra', 170, 'operaciones'),
  ('construccion-inmobiliario-certificaciones-leed-breeam-y-construccion-verde', 'construccion-inmobiliario', 'Certificaciones LEED, BREEAM y construcción verde', 180, 'operaciones'),
  ('construccion-inmobiliario-ingenieria-estructural-de-precision', 'construccion-inmobiliario', 'Ingeniería estructural de precisión', 190, 'operaciones'),
  ('construccion-inmobiliario-instalaciones-mep-y-especialidades', 'construccion-inmobiliario', 'Instalaciones MEP y especialidades', 200, 'operaciones'),
  ('construccion-inmobiliario-project-finance-y-estructuracion-inmobiliaria', 'construccion-inmobiliario', 'Project finance y estructuración inmobiliaria', 210, 'operaciones'),
  ('construccion-inmobiliario-asset-y-property-management', 'construccion-inmobiliario', 'Asset y property management', 220, 'operaciones'),
  ('construccion-inmobiliario-brokerage-y-transacciones-comerciales', 'construccion-inmobiliario', 'Brokerage y transacciones comerciales', 230, 'operaciones'),
  ('construccion-inmobiliario-desarrollo-de-loteos-y-uso-de-suelo-mixto', 'construccion-inmobiliario', 'Desarrollo de loteos y uso de suelo mixto', 240, 'operaciones'),
  ('construccion-inmobiliario-logistica-industrial-y-parques', 'construccion-inmobiliario', 'Logística industrial y parques', 250, 'operaciones'),
  ('construccion-inmobiliario-hospitality-real-estate-y-mixed-use', 'construccion-inmobiliario', 'Hospitality real estate y mixed-use', 260, 'operaciones'),
  ('construccion-inmobiliario-due-diligence-tecnica-y-estudios-de-prefactibilidad', 'construccion-inmobiliario', 'Due diligence técnica y estudios de prefactibilidad', 270, 'operaciones'),
  ('construccion-inmobiliario-mantenimiento-predictivo-de-inmuebles', 'construccion-inmobiliario', 'Mantenimiento predictivo de inmuebles', 280, 'operaciones'),
  ('construccion-inmobiliario-edificios-inteligentes-y-sistemas-integrados', 'construccion-inmobiliario', 'Edificios inteligentes y sistemas integrados', 290, 'operaciones'),
  ('construccion-inmobiliario-topografia-levantamientos-y-lidar', 'construccion-inmobiliario', 'Topografía, levantamientos y lidar', 300, 'operaciones'),
  ('construccion-inmobiliario-permisos-impacto-urbano-y-compliance-regulatorio', 'construccion-inmobiliario', 'Permisos, impacto urbano y compliance regulatorio', 310, 'operaciones'),
  ('construccion-inmobiliario-real-estate-proptech-y-captacion-digital', 'construccion-inmobiliario', 'Real estate proptech y captación digital', 320, 'operaciones'),
  ('manufactura-industria-lean-manufacturing-y-mejora-continua', 'manufactura-industria', 'Lean manufacturing y mejora continua', 150, 'operaciones'),
  ('manufactura-industria-tpm-y-confiabilidad-operativa', 'manufactura-industria', 'TPM y confiabilidad operativa', 160, 'operaciones'),
  ('manufactura-industria-industria-4-0-sensorica-y-analytics-de-planta', 'manufactura-industria', 'Industria 4.0, sensórica y analytics de planta', 170, 'operaciones'),
  ('manufactura-industria-robotizacion-y-cobots', 'manufactura-industria', 'Robotización y cobots', 180, 'operaciones'),
  ('manufactura-industria-quimica-fina-y-especialidades', 'manufactura-industria', 'Química fina y especialidades', 190, 'operaciones'),
  ('manufactura-industria-farmoquimica-y-sintesis-industrial', 'manufactura-industria', 'Farmoquímica y síntesis industrial', 200, 'operaciones'),
  ('manufactura-industria-bebidas-y-agua-embotellada', 'manufactura-industria', 'Bebidas y agua embotellada', 210, 'operaciones'),
  ('manufactura-industria-cosmetica-fragrance-y-cuidado-personal-industrial', 'manufactura-industria', 'Cosmética, fragrance y cuidado personal industrial', 220, 'operaciones'),
  ('manufactura-industria-papel-celulosa-y-embalajes-fibra', 'manufactura-industria', 'Papel, celulosa y embalajes fibra', 230, 'operaciones'),
  ('manufactura-industria-vidrio-ceramica-tecnica-y-refractarios', 'manufactura-industria', 'Vidrio, cerámica técnica y refractarios', 240, 'operaciones'),
  ('manufactura-industria-mineria-metalurgia-y-fundicion', 'manufactura-industria', 'Minería, metalurgia y fundición', 250, 'operaciones'),
  ('manufactura-industria-simulacion-de-planta-y-plant-layout', 'manufactura-industria', 'Simulación de planta y plant layout', 260, 'operaciones'),
  ('manufactura-industria-compras-estrategicas-y-sourcing-global', 'manufactura-industria', 'Compras estratégicas y sourcing global', 270, 'operaciones'),
  ('manufactura-industria-manufactura-para-exportacion-y-nearshoring', 'manufactura-industria', 'Manufactura para exportación y nearshoring', 280, 'operaciones'),
  ('manufactura-industria-esquemas-de-maquila-y-subcontratacion', 'manufactura-industria', 'Esquemas de maquila y subcontratación', 290, 'operaciones'),
  ('manufactura-industria-materiales-compuestos-y-biopolimeros', 'manufactura-industria', 'Materiales compuestos y biopolímeros', 300, 'operaciones'),
  ('manufactura-industria-energia-termica-y-utilities-de-planta', 'manufactura-industria', 'Energía térmica y utilities de planta', 310, 'operaciones'),
  ('manufactura-industria-calibracion-metrologica-y-laboratorio-industrial', 'manufactura-industria', 'Calibración metrológica y laboratorio industrial', 320, 'operaciones'),
  ('manufactura-industria-reverse-logistics-industrial', 'manufactura-industria', 'Reverse logistics industrial', 330, 'operaciones'),
  ('manufactura-industria-puesta-en-marcha-y-commissioning', 'manufactura-industria', 'Puesta en marcha y commissioning', 340, 'operaciones'),
  ('agro-alimentacion-hidroponia-invernaderos-y-agricultura-vertical', 'agro-alimentacion', 'Hidroponía, invernaderos y agricultura vertical', 140, 'operaciones'),
  ('agro-alimentacion-agricultura-de-precision-y-agrodrones', 'agro-alimentacion', 'Agricultura de precisión y agrodrones', 150, 'operaciones'),
  ('agro-alimentacion-semillas-biotecnologia-vegetal-y-fitomejoramiento', 'agro-alimentacion', 'Semillas, biotecnología vegetal y fitomejoramiento', 160, 'operaciones'),
  ('agro-alimentacion-insumos-fertilizacion-y-nutricion-de-cultivos', 'agro-alimentacion', 'Insumos, fertilización y nutrición de cultivos', 170, 'operaciones'),
  ('agro-alimentacion-fitosanidad-y-manejo-integrado-de-plagas', 'agro-alimentacion', 'Fitosanidad y manejo integrado de plagas', 180, 'operaciones'),
  ('agro-alimentacion-lacteos-quesos-y-derivados-industriales', 'agro-alimentacion', 'Lácteos, quesos y derivados industriales', 190, 'operaciones'),
  ('agro-alimentacion-carnicos-aves-y-productos-transformados', 'agro-alimentacion', 'Cárnicos, aves y productos transformados', 200, 'operaciones'),
  ('agro-alimentacion-panaderia-molinos-y-harinas-industriales', 'agro-alimentacion', 'Panadería, molinos y harinas industriales', 210, 'operaciones'),
  ('agro-alimentacion-cacao-cafe-y-commodity-de-altura', 'agro-alimentacion', 'Cacao, café y commodity de altura', 220, 'operaciones'),
  ('agro-alimentacion-retail-alimentario-y-abasto-moderno', 'agro-alimentacion', 'Retail alimentario y abasto moderno', 230, 'operaciones'),
  ('agro-alimentacion-inocuidad-haccp-y-cultura-de-calidad', 'agro-alimentacion', 'Inocuidad HACCP y cultura de calidad', 240, 'operaciones'),
  ('agro-alimentacion-trazabilidad-cadena-de-frio-y-ultima-milla-alimentaria', 'agro-alimentacion', 'Trazabilidad, cadena de frío y última milla alimentaria', 250, 'operaciones'),
  ('agro-alimentacion-bebidas-fermentadas-y-destilados-artesanales', 'agro-alimentacion', 'Bebidas fermentadas y destilados artesanales', 260, 'operaciones'),
  ('agro-alimentacion-pesca-acuicultura-industrial-y-valor-agregado', 'agro-alimentacion', 'Pesca, acuicultura industrial y valor agregado', 270, 'operaciones'),
  ('agro-alimentacion-apicultura-y-polinizacion-comercial', 'agro-alimentacion', 'Apicultura y polinización comercial', 280, 'operaciones'),
  ('agro-alimentacion-foresteria-comercial-y-aserradero', 'agro-alimentacion', 'Forestería comercial y aserradero', 290, 'operaciones'),
  ('agro-alimentacion-biocombustibles-y-oleoquimicos-agricolas', 'agro-alimentacion', 'Biocombustibles y oleoquímicos agrícolas', 300, 'operaciones'),
  ('agro-alimentacion-comercializacion-agricola-y-desk-de-commodities', 'agro-alimentacion', 'Comercialización agrícola y desk de commodities', 310, 'operaciones'),
  ('agro-alimentacion-cooperativas-asociaciones-y-extensionismo', 'agro-alimentacion', 'Cooperativas, asociaciones y extensionismo', 320, 'operaciones'),
  ('agro-alimentacion-nutricion-animal-y-formulacion-de-alimento-balanceado', 'agro-alimentacion', 'Nutrición animal y formulación de alimento balanceado', 330, 'operaciones'),
  ('gobierno-sector-publico-proteccion-civil-y-gestion-de-emergencias', 'gobierno-sector-publico', 'Protección civil y gestión de emergencias', 150, 'negocio'),
  ('gobierno-sector-publico-procuracion-e-imparticion-de-justicia', 'gobierno-sector-publico', 'Procuración e impartición de justicia', 160, 'negocio'),
  ('gobierno-sector-publico-hacienda-publica-y-finanzas-gubernamentales', 'gobierno-sector-publico', 'Hacienda pública y finanzas gubernamentales', 170, 'negocio'),
  ('gobierno-sector-publico-compras-publicas-y-adquisiciones-estrategicas', 'gobierno-sector-publico', 'Compras públicas y adquisiciones estratégicas', 180, 'negocio'),
  ('gobierno-sector-publico-datos-abiertos-e-interoperabilidad', 'gobierno-sector-publico', 'Datos abiertos e interoperabilidad', 190, 'negocio'),
  ('gobierno-sector-publico-gobierno-digital-y-servicios-en-linea', 'gobierno-sector-publico', 'Gobierno digital y servicios en línea', 200, 'negocio'),
  ('gobierno-sector-publico-participacion-ciudadana-y-presupuesto-participativo', 'gobierno-sector-publico', 'Participación ciudadana y presupuesto participativo', 210, 'negocio'),
  ('gobierno-sector-publico-ordenamiento-territorial-y-uso-de-suelo', 'gobierno-sector-publico', 'Ordenamiento territorial y uso de suelo', 220, 'negocio'),
  ('gobierno-sector-publico-politicas-educativas-publicas', 'gobierno-sector-publico', 'Políticas educativas públicas', 230, 'negocio'),
  ('gobierno-sector-publico-infraestructura-publica-y-app', 'gobierno-sector-publico', 'Infraestructura pública y APP', 240, 'negocio'),
  ('gobierno-sector-publico-areas-naturales-protegidas-y-anp', 'gobierno-sector-publico', 'Áreas naturales protegidas y ANP', 250, 'negocio'),
  ('gobierno-sector-publico-cultura-patrimonio-y-memoria', 'gobierno-sector-publico', 'Cultura, patrimonio y memoria', 260, 'negocio'),
  ('gobierno-sector-publico-estadistica-oficial-y-censos', 'gobierno-sector-publico', 'Estadística oficial y censos', 270, 'negocio'),
  ('gobierno-sector-publico-planeacion-del-desarrollo', 'gobierno-sector-publico', 'Planeación del desarrollo', 280, 'negocio'),
  ('gobierno-sector-publico-cooperacion-internacional-para-el-desarrollo', 'gobierno-sector-publico', 'Cooperación internacional para el desarrollo', 290, 'negocio'),
  ('gobierno-sector-publico-capital-humano-y-carrera-administrativa', 'gobierno-sector-publico', 'Capital humano y carrera administrativa', 300, 'negocio'),
  ('gobierno-sector-publico-organismos-autonomos-y-reguladores-sectoriales', 'gobierno-sector-publico', 'Organismos autónomos y reguladores sectoriales', 310, 'negocio'),
  ('gobierno-sector-publico-innovacion-publica-y-laboratorios-de-politica', 'gobierno-sector-publico', 'Innovación pública y laboratorios de política', 320, 'negocio'),
  ('gobierno-sector-publico-seguridad-nacional-y-enfoque-multidimensional', 'gobierno-sector-publico', 'Seguridad nacional y enfoque multidimensional', 330, 'negocio'),
  ('gobierno-sector-publico-fomento-economico-y-clusters-regionales', 'gobierno-sector-publico', 'Fomento económico y clusters regionales', 340, 'negocio'),
  ('turismo-hospitalidad-revenue-management-y-distribucion-hotelera', 'turismo-hospitalidad', 'Revenue management y distribución hotelera', 140, 'negocio'),
  ('turismo-hospitalidad-housekeeping-y-operaciones-de-habitaciones', 'turismo-hospitalidad', 'Housekeeping y operaciones de habitaciones', 150, 'negocio'),
  ('turismo-hospitalidad-f-b-hotelero-y-banqueteria', 'turismo-hospitalidad', 'F&B hotelero y banquetería', 160, 'negocio'),
  ('turismo-hospitalidad-mice-y-congresos', 'turismo-hospitalidad', 'MICE y congresos', 170, 'negocio'),
  ('turismo-hospitalidad-oficinas-de-turismo-y-gestion-de-destino', 'turismo-hospitalidad', 'Oficinas de turismo y gestión de destino', 180, 'negocio'),
  ('turismo-hospitalidad-turismo-religioso-y-peregrinaciones', 'turismo-hospitalidad', 'Turismo religioso y peregrinaciones', 190, 'negocio'),
  ('turismo-hospitalidad-turismo-de-naturaleza-y-observacion', 'turismo-hospitalidad', 'Turismo de naturaleza y observación', 200, 'negocio'),
  ('turismo-hospitalidad-ecoturismo-certificado', 'turismo-hospitalidad', 'Ecoturismo certificado', 210, 'negocio'),
  ('turismo-hospitalidad-rentas-vacacionales-y-hospitality-alternativo', 'turismo-hospitalidad', 'Rentas vacacionales y hospitality alternativo', 220, 'negocio'),
  ('turismo-hospitalidad-hostels-glamping-y-coliving-viajero', 'turismo-hospitalidad', 'Hostels, glamping y coliving viajero', 230, 'negocio'),
  ('turismo-hospitalidad-hospitalidad-de-lujo-y-personalizacion', 'turismo-hospitalidad', 'Hospitalidad de lujo y personalización', 240, 'negocio'),
  ('turismo-hospitalidad-integracion-de-casino-resort-y-entretenimiento', 'turismo-hospitalidad', 'Integración de casino-resort y entretenimiento', 250, 'negocio'),
  ('turismo-hospitalidad-parques-tematicos-y-atracciones', 'turismo-hospitalidad', 'Parques temáticos y atracciones', 260, 'negocio'),
  ('turismo-hospitalidad-wellness-tourism-y-spas-destino', 'turismo-hospitalidad', 'Wellness tourism y spas destino', 270, 'negocio'),
  ('turismo-hospitalidad-turismo-deportivo-y-megaeventos', 'turismo-hospitalidad', 'Turismo deportivo y megaeventos', 280, 'negocio'),
  ('turismo-hospitalidad-turismo-lgbtq-friendly', 'turismo-hospitalidad', 'Turismo LGBTQ+ friendly', 290, 'negocio'),
  ('turismo-hospitalidad-turismo-accesible-y-diseno-inclusivo', 'turismo-hospitalidad', 'Turismo accesible y diseño inclusivo', 300, 'negocio'),
  ('turismo-hospitalidad-producto-digital-y-apps-de-destino', 'turismo-hospitalidad', 'Producto digital y apps de destino', 310, 'negocio'),
  ('turismo-hospitalidad-asistencia-al-viajero-y-seguros-turisticos', 'turismo-hospitalidad', 'Asistencia al viajero y seguros turísticos', 320, 'negocio'),
  ('turismo-hospitalidad-experiencias-gastronomicas-destacadas', 'turismo-hospitalidad', 'Experiencias gastronómicas destacadas', 330, 'negocio'),
  ('energia-sustentabilidad-almacenamiento-distribuido-y-bess', 'energia-sustentabilidad', 'Almacenamiento distribuido y BESS', 130, 'ciencia'),
  ('energia-sustentabilidad-redes-inteligentes-y-flexibilidad', 'energia-sustentabilidad', 'Redes inteligentes y flexibilidad', 140, 'ciencia'),
  ('energia-sustentabilidad-geotermia-y-bombeo-termico', 'energia-sustentabilidad', 'Geotermia y bombeo térmico', 150, 'ciencia'),
  ('energia-sustentabilidad-biogas-digestion-anaerobica-y-gestion-de-finos', 'energia-sustentabilidad', 'Biogás, digestión anaeróbica y gestión de finos', 160, 'ciencia'),
  ('energia-sustentabilidad-captura-uso-y-almacenamiento-de-carbono', 'energia-sustentabilidad', 'Captura, uso y almacenamiento de carbono', 170, 'ciencia'),
  ('energia-sustentabilidad-mercados-de-carbono-y-mrv', 'energia-sustentabilidad', 'Mercados de carbono y MRV', 180, 'ciencia'),
  ('energia-sustentabilidad-certificaciones-ambientales-sectoriales', 'energia-sustentabilidad', 'Certificaciones ambientales sectoriales', 190, 'ciencia'),
  ('energia-sustentabilidad-gestion-hidrica-y-plantas-de-tratamiento', 'energia-sustentabilidad', 'Gestión hídrica y plantas de tratamiento', 200, 'ciencia'),
  ('energia-sustentabilidad-biodiversidad-offsets-y-bancos-de-habitat', 'energia-sustentabilidad', 'Biodiversidad, offsets y bancos de hábitat', 210, 'ciencia'),
  ('energia-sustentabilidad-impacto-ambiental-y-licencias-sectoriales', 'energia-sustentabilidad', 'Impacto ambiental y licencias sectoriales', 220, 'ciencia'),
  ('energia-sustentabilidad-due-diligence-ambiental-y-m-a-verde', 'energia-sustentabilidad', 'Due diligence ambiental y M&A verde', 230, 'ciencia'),
  ('energia-sustentabilidad-energia-nuclear-servicios-y-regulacion', 'energia-sustentabilidad', 'Energía nuclear (servicios y regulación)', 240, 'ciencia'),
  ('energia-sustentabilidad-mineria-responsable-y-cierre-de-minas', 'energia-sustentabilidad', 'Minería responsable y cierre de minas', 250, 'ciencia'),
  ('energia-sustentabilidad-transicion-justa-y-reconversion-industrial', 'energia-sustentabilidad', 'Transición justa y reconversión industrial', 260, 'ciencia'),
  ('energia-sustentabilidad-movilidad-urbana-baja-en-emisiones', 'energia-sustentabilidad', 'Movilidad urbana baja en emisiones', 270, 'ciencia'),
  ('energia-sustentabilidad-edificaciones-net-zero-y-envelopes-eficientes', 'energia-sustentabilidad', 'Edificaciones net-zero y envelopes eficientes', 280, 'ciencia'),
  ('energia-sustentabilidad-suelos-y-agricultura-climaticamente-inteligente', 'energia-sustentabilidad', 'Suelos y agricultura climáticamente inteligente', 290, 'ciencia'),
  ('energia-sustentabilidad-energia-oceanica-y-mareomotriz', 'energia-sustentabilidad', 'Energía oceánica y mareomotriz', 300, 'ciencia'),
  ('energia-sustentabilidad-reportes-tcfd-y-disclosure-climatico', 'energia-sustentabilidad', 'Reportes TCFD y disclosure climático', 310, 'ciencia'),
  ('energia-sustentabilidad-generacion-distribuida-y-microrredes', 'energia-sustentabilidad', 'Generación distribuida y microrredes', 320, 'ciencia'),
  ('retail-comercio-pricing-y-estrategia-omnicanal', 'retail-comercio', 'Pricing y estrategia omnicanal', 130, 'negocio'),
  ('retail-comercio-revenue-management-retail', 'retail-comercio', 'Revenue management retail', 140, 'negocio'),
  ('retail-comercio-planogramas-layout-y-shopper-marketing', 'retail-comercio', 'Planogramas, layout y shopper marketing', 150, 'negocio'),
  ('retail-comercio-fulfillment-dark-stores-y-ultima-milla', 'retail-comercio', 'Fulfillment, dark stores y última milla', 160, 'negocio'),
  ('retail-comercio-quick-commerce-y-entregas-instantaneas', 'retail-comercio', 'Quick commerce y entregas instantáneas', 170, 'negocio'),
  ('retail-comercio-social-commerce-y-live-shopping', 'retail-comercio', 'Social commerce y live shopping', 180, 'negocio'),
  ('retail-comercio-marcas-d2c-y-flagship-digital', 'retail-comercio', 'Marcas D2C y flagship digital', 190, 'negocio'),
  ('retail-comercio-outlet-off-price-y-inventarios-estrategicos', 'retail-comercio', 'Outlet, off-price y inventarios estratégicos', 200, 'negocio'),
  ('retail-comercio-mayoreo-b2b-y-cash-carry', 'retail-comercio', 'Mayoreo B2B y cash & carry', 210, 'negocio'),
  ('retail-comercio-trade-marketing-y-ejecucion-en-punto-de-venta', 'retail-comercio', 'Trade marketing y ejecución en punto de venta', 220, 'negocio'),
  ('retail-comercio-analitica-retail-y-forecasting-de-demanda', 'retail-comercio', 'Analítica retail y forecasting de demanda', 230, 'negocio'),
  ('retail-comercio-prevencion-de-mermas-y-loss-prevention', 'retail-comercio', 'Prevención de mermas y loss prevention', 240, 'negocio'),
  ('retail-comercio-loyalty-crm-y-datos-first-party', 'retail-comercio', 'Loyalty, CRM y datos first-party', 250, 'negocio'),
  ('retail-comercio-tiendas-concepto-y-flagship-fisicas', 'retail-comercio', 'Tiendas concepto y flagship físicas', 260, 'negocio'),
  ('retail-comercio-retail-efimero-y-pop-up-stores', 'retail-comercio', 'Retail efímero y pop-up stores', 270, 'negocio'),
  ('retail-comercio-retail-en-centros-comerciales', 'retail-comercio', 'Retail en centros comerciales', 280, 'negocio'),
  ('retail-comercio-retail-internacional-aranceles-y-compliance', 'retail-comercio', 'Retail internacional, aranceles y compliance', 290, 'negocio'),
  ('retail-comercio-marca-propia-y-sourcing-de-private-label', 'retail-comercio', 'Marca propia y sourcing de private label', 300, 'negocio'),
  ('retail-comercio-canales-informales-ferias-y-micromercados', 'retail-comercio', 'Canales informales, ferias y micromercados', 310, 'negocio'),
  ('retail-comercio-cdp-analitica-omnicanal-y-personalizacion', 'retail-comercio', 'CDP, analítica omnicanal y personalización', 320, 'negocio'),
  ('legal-consultoria-litigio-civil-y-mercantil', 'legal-consultoria', 'Litigio civil y mercantil', 130, 'negocio'),
  ('legal-consultoria-arbitraje-nacional-e-internacional', 'legal-consultoria', 'Arbitraje nacional e internacional', 140, 'negocio'),
  ('legal-consultoria-derecho-de-familia-y-sucesiones', 'legal-consultoria', 'Derecho de familia y sucesiones', 150, 'negocio'),
  ('legal-consultoria-derecho-inmobiliario-y-condominales', 'legal-consultoria', 'Derecho inmobiliario y condominales', 160, 'negocio'),
  ('legal-consultoria-fusiones-y-adquisiciones-m-a', 'legal-consultoria', 'Fusiones y adquisiciones (M&A)', 170, 'negocio'),
  ('legal-consultoria-capital-markets-y-ofertas-publicas', 'legal-consultoria', 'Capital markets y ofertas públicas', 180, 'negocio'),
  ('legal-consultoria-privacidad-datos-personales-y-ciberlegal', 'legal-consultoria', 'Privacidad, datos personales y ciberlegal', 190, 'negocio'),
  ('legal-consultoria-contratos-tecnologicos-y-outsourcing-it', 'legal-consultoria', 'Contratos tecnológicos y outsourcing IT', 200, 'negocio'),
  ('legal-consultoria-derecho-penal-corporativo-y-compliance-penal', 'legal-consultoria', 'Derecho penal corporativo y compliance penal', 210, 'negocio'),
  ('legal-consultoria-planeacion-fiscal-avanzada-y-controversia', 'legal-consultoria', 'Planeación fiscal avanzada y controversia', 220, 'negocio'),
  ('legal-consultoria-consultoria-operativa-y-mejoras-de-procesos', 'legal-consultoria', 'Consultoría operativa y mejoras de procesos', 230, 'negocio'),
  ('legal-consultoria-advisory-tecnologico-y-transformacion-digital', 'legal-consultoria', 'Advisory tecnológico y transformación digital', 240, 'negocio'),
  ('legal-consultoria-executive-search-de-alto-nivel', 'legal-consultoria', 'Executive search de alto nivel', 250, 'negocio'),
  ('legal-consultoria-cultura-organizacional-y-engagement', 'legal-consultoria', 'Cultura organizacional y engagement', 260, 'negocio'),
  ('legal-consultoria-desarrollo-de-liderazgo-y-coaching-ejecutivo', 'legal-consultoria', 'Desarrollo de liderazgo y coaching ejecutivo', 270, 'negocio'),
  ('legal-consultoria-gestion-del-desempeno-y-okrs', 'legal-consultoria', 'Gestión del desempeño y OKRs', 280, 'negocio'),
  ('legal-consultoria-compensacion-nomina-estrategica-y-equity', 'legal-consultoria', 'Compensación, nómina estratégica y equity', 290, 'negocio'),
  ('legal-consultoria-people-analytics-y-workforce-planning', 'legal-consultoria', 'People analytics y workforce planning', 300, 'negocio'),
  ('legal-consultoria-relaciones-laborales-sindicales-y-negociacion-colectiva', 'legal-consultoria', 'Relaciones laborales, sindicales y negociación colectiva', 310, 'negocio'),
  ('legal-consultoria-servicios-integrales-de-hr-outsourcing', 'legal-consultoria', 'Servicios integrales de HR outsourcing', 320, 'negocio'),
  ('deporte-bienestar-entrenamiento-personal-y-coaching-one-on-one', 'deporte-bienestar', 'Entrenamiento personal y coaching one-on-one', 130, 'producto'),
  ('deporte-bienestar-fuerza-powerlifting-y-entrenamiento-de-rendimiento', 'deporte-bienestar', 'Fuerza, powerlifting y entrenamiento de rendimiento', 140, 'producto'),
  ('deporte-bienestar-running-trail-y-endurance', 'deporte-bienestar', 'Running, trail y endurance', 150, 'producto'),
  ('deporte-bienestar-natacion-triatlon-y-deportes-acuaticos', 'deporte-bienestar', 'Natación, triatlón y deportes acuáticos', 160, 'producto'),
  ('deporte-bienestar-ciclismo-indoor-outdoor-y-indoor-training-tech', 'deporte-bienestar', 'Ciclismo indoor, outdoor y indoor training tech', 170, 'producto'),
  ('deporte-bienestar-functional-fitness-y-hiit', 'deporte-bienestar', 'Functional fitness y HIIT', 180, 'producto'),
  ('deporte-bienestar-danza-fitness-y-coreografias-grupales', 'deporte-bienestar', 'Danza fitness y coreografías grupales', 190, 'producto'),
  ('deporte-bienestar-artes-marciales-y-combate-deportivo', 'deporte-bienestar', 'Artes marciales y combate deportivo', 200, 'producto'),
  ('deporte-bienestar-montanismo-escalada-y-outdoor-sports', 'deporte-bienestar', 'Montañismo, escalada y outdoor sports', 210, 'producto'),
  ('deporte-bienestar-nutricion-deportiva-suplementada', 'deporte-bienestar', 'Nutrición deportiva suplementada', 220, 'producto'),
  ('deporte-bienestar-fisioterapia-y-readaptacion-al-esfuerzo', 'deporte-bienestar', 'Fisioterapia y readaptación al esfuerzo', 230, 'producto'),
  ('deporte-bienestar-recuperacion-contrast-therapy-y-sueno', 'deporte-bienestar', 'Recuperación, contrast therapy y sueño', 240, 'producto'),
  ('deporte-bienestar-analitica-de-rendimiento-y-wearables', 'deporte-bienestar', 'Analítica de rendimiento y wearables', 250, 'producto'),
  ('deporte-bienestar-marketing-deportivo-y-activaciones', 'deporte-bienestar', 'Marketing deportivo y activaciones', 260, 'producto'),
  ('deporte-bienestar-patrocinios-naming-rights-y-hospitality-deportiva', 'deporte-bienestar', 'Patrocinios, naming rights y hospitality deportiva', 270, 'producto'),
  ('deporte-bienestar-derecho-deportivo-y-agentes', 'deporte-bienestar', 'Derecho deportivo y agentes', 280, 'producto'),
  ('deporte-bienestar-diseno-y-operacion-de-instalaciones-deportivas', 'deporte-bienestar', 'Diseño y operación de instalaciones deportivas', 290, 'producto'),
  ('deporte-bienestar-escuelas-formativas-y-captacion-de-talento-joven', 'deporte-bienestar', 'Escuelas formativas y captación de talento joven', 300, 'producto'),
  ('deporte-bienestar-turismo-activo-y-deporte-experiencial', 'deporte-bienestar', 'Turismo activo y deporte experiencial', 310, 'producto'),
  ('deporte-bienestar-salud-mental-y-mindfulness-aplicado-al-deporte', 'deporte-bienestar', 'Salud mental y mindfulness aplicado al deporte', 320, 'producto')
ON CONFLICT (slug) DO NOTHING;
